var db = require("./modules/db.js");
var json = [
     {
        "tNumber": "1",
        "school": "湖南工业大学",
        "school2": "Hunan University of Technology",
        "type": "竞赛费",
        "bank": "中国建设银行株洲城东支行",
        "taxNum": "430211445175364",
        "addr": "湖南省株洲市天元区泰山路88号",
        "schoolContactName": "高雨亭",
        "schoolContactPhone": "15973336911",
        "coach": "邓晓军",
        "coach2": "Deng Xiaojun",
        "coachPhone": "13873358664",
        "coachEmail": "hngydxjsjxy@163.com",
        "isCome": "否",
        "cSize": 0,
        "tName": "赞美太阳",
        "tNameE": "HUT_1 ",
        "tPerson1": "曹巍",
        "tPerson1E": "Cao Wei",
        "sex1": "男",
        "phone1": "17670658689",
        "p1Size": "XL",
        "tPerson2": "卢俊峰",
        "tPerson2E": "Lu Junfeng",
        "sex2": "男",
        "phone2": "15773330213",
        "p2Size": "XL",
        "tPerson3": "高雨亭",
        "tPerson3E": "Gao Yuting",
        "sex3": "男",
        "phone3": "15973336911",
        "p3Size": "XL"
    },
    {
        "tNumber": "2",
        "school": "宁波大学",
        "school2": "Ningbo University",
        "type": "会议费",
        "bank": "宁波市江北区",
        "taxNum": "123300004195291066",
        "addr": "浙江宁波江北区风华路818号宁波大学信息学院",
        "schoolContactName": "陈叶芳",
        "schoolContactPhone": "13567902457",
        "coach": "陈叶芳",
        "coach2": "Yefang Chen",
        "coachPhone": "13567902457",
        "coachEmail": "chenyefang@nbu.edu.cn",
        "isCome": "是 ",
        "cSize": "L",
        "tName": "上课摸鱼",
        "tNameE": "fishing when study",
        "tPerson1": "潘凌超",
        "tPerson1E": "Lingchao Pan",
        "sex1": "男",
        "phone1": "18888641195",
        "p1Size": "XL",
        "tPerson2": "沈鸿",
        "tPerson2E": "Hong Shen",
        "sex2": "男",
        "phone2": "18888641065",
        "p2Size": "XXL",
        "tPerson3": "钟家平",
        "tPerson3E": "Jiaping Zhong",
        "sex3": "男",
        "phone3": "15057400454",
        "p3Size": "XL"
    },
    {
        "tNumber": "3",
        "school": "湖南大学",
        "school2": "Hunan University",
        "type": "竞赛费",
        "bank": "中国银行长沙市湖南大学支行",
        "taxNum": "430104444885399",
        "addr": "湖南省长沙市岳麓区湖南大学天马学生公寓",
        "schoolContactName": "谭开君",
        "schoolContactPhone": "15616151725",
        "coach": "吴昊",
        "coach2": "Wu Hao",
        "coachPhone": "13317315137",
        "coachEmail": "jt_wh@hnu.edu.cn",
        "isCome": "是",
        "cSize": "L",
        "tName": "熊宝宝",
        "tNameE": "BearBaby ",
        "tPerson1": "谭开君",
        "tPerson1E": "TanKaijun",
        "sex1": "男",
        "phone1": "15616151725",
        "p1Size": "XL",
        "tPerson2": "唐大海",
        "tPerson2E": "TangDahai",
        "sex2": "男",
        "phone2": "18684765389",
        "p2Size": "XL",
        "tPerson3": "赵雄君",
        "tPerson3E": "ZhaoXiongjun",
        "sex3": "男",
        "phone3": "18998377505",
        "p3Size": "XL"
    },
    {
        "tNumber": "4",
        "school": "香港大学",
        "school2": "The University of Hong Kong",
        "type": "竞赛费",
        "bank": "不适用",
        "taxNum": "不适用",
        "addr": "Room LG 101, Chow Yei Ching Building, Department of Computer Science, The University of Hong Kong, Pokfulam, Hong Kong",
        "schoolContactName": "孙斌韬 (SUN Bintao)",
        "schoolContactPhone": "+852 69332365",
        "coach": "张晨孜",
        "coach2": "ZHANG Chenzi",
        "coachPhone": "+852 51358275",
        "coachEmail": "czzhang@cs.hku.hk",
        "isCome": "是",
        "cSize": "L",
        "tName": "龜速跑者",
        "tNameE": "Turtle Racer",
        "tPerson1": "鄧智仁",
        "tPerson1E": "TANG Chi Ian",
        "sex1": "男",
        "phone1": "+852 62102977",
        "p1Size": "M",
        "tPerson2": "-",
        "tPerson2E": "SINGH Divyansh",
        "sex2": "男",
        "phone2": "+852 54916267",
        "p2Size": "M",
        "tPerson3": "王因琪",
        "tPerson3E": "WANG Michelle Yih-chyan",
        "sex3": "女",
        "phone3": "+852 97943161",
        "p3Size": "M"
    },
    {
        "tNumber": "5",
        "school": "成都信息工程大学",
        "school2": "Chengdu University of Information Technology",
        "type": "竞赛费",
        "bank": "中行双流西航港支行",
        "taxNum": "1251 0000 450 717 80XR\n",
        "addr": "四川省成都市双流县西航港街道成都信息工程大学",
        "schoolContactName": "袁曦焜",
        "schoolContactPhone": "18783846577",
        "coach": "黄健",
        "coach2": "Jian Huang",
        "coachPhone": "18783846577",
        "coachEmail": "960448968@qq.com",
        "isCome": "是",
        "cSize": "L",
        "tName": "Chobi17",
        "tNameE": "Chobi17",
        "tPerson1": "林湖龙",
        "tPerson1E": "HuLong Lin",
        "sex1": "男",
        "phone1": "15208381747",
        "p1Size": "L",
        "tPerson2": "谢仁义",
        "tPerson2E": "RenYi Xie",
        "sex2": "男",
        "phone2": "18200326751",
        "p2Size": "XL",
        "tPerson3": "陈彦君",
        "tPerson3E": "YanJun Chen",
        "sex3": "男",
        "phone3": "18200316052",
        "p3Size": "XL"
    },
     {
        "tNumber": "6",
        "school": "河海大学",
        "school2": "Hohai University",
        "type": "竞赛费",
        "bank": "南京市西康路1号",
        "taxNum": "121000004660068699",
        "addr": "南京市江宁区佛城西路8号河海大学",
        "schoolContactName": "朱云",
        "schoolContactPhone": "15951719864",
        "coach": "张雪洁",
        "coach2": "Xuejie Zhang",
        "coachPhone": "15951719864",
        "coachEmail": "jxy_cxsys@163.com",
        "isCome": "否",
        "cSize": 0,
        "tName": "请看英文名",
        "tNameE": "Don't wary，lixiyi's wdf\n",
        "tPerson1": "王狄烽",
        "tPerson1E": "Difeng Wang",
        "sex1": "男",
        "phone1": "15189800529",
        "p1Size": "M",
        "tPerson2": "连晓颖",
        "tPerson2E": "Xiaoying Lian",
        "sex2": "女",
        "phone2": "15150681051",
        "p2Size": "M",
        "tPerson3": "王睿",
        "tPerson3E": "Rui Wang",
        "sex3": "男",
        "phone3": "15195890059",
        "p3Size": "M"
    },
    {
        "tNumber": "7",
        "school": "中山大学",
        "school2": "Sun Yat-sen University",
        "type": "会务费",
        "bank": "中国工商银行广州中山大学支行",
        "taxNum": "121000004558631445",
        "addr": "广州大学城中山大学东校园数据科学与计算机学院616E",
        "schoolContactName": "林瀚",
        "schoolContactPhone": "13711174851",
        "coach": "郭嵩山/林瀚",
        "coach2": "Songshan Guo/Han Lin",
        "coachPhone": "13711174851",
        "coachEmail": "linhan095@gmail.com",
        "isCome": "是",
        "cSize": "S",
        "tName": "中山大学_死线之蓝",
        "tNameE": "SYSU_DeadBlue",
        "tPerson1": "吴统文",
        "tPerson1E": "tongwen wu",
        "sex1": "男",
        "phone1": "13719326757",
        "p1Size": "L",
        "tPerson2": "刘明航",
        "tPerson2E": "minghang liu",
        "sex2": "男",
        "phone2": "15880405959",
        "p2Size": "L",
        "tPerson3": "杨思翔",
        "tPerson3E": "sixiang yang",
        "sex3": "男",
        "phone3": "13719198199",
        "p3Size": "XL"
    },
     {
        "tNumber": "8",
        "school": "华中农业大学",
        "school2": "Huazhong Agricultural University",
        "type": "会务费",
        "bank": "中国银行武汉华农支行",
        "taxNum": "420111420004817",
        "addr": "湖北省武汉市狮子山路1号华中农业大学",
        "schoolContactName": "倪福川",
        "schoolContactPhone": "18602714039",
        "coach": "倪福川",
        "coach2": "Fuchuan Ni",
        "coachPhone": "18602714039",
        "coachEmail": "acm@mail.hzau.edu.cn",
        "isCome": "是",
        "cSize": "XXL",
        "tName": "胖胖斌",
        "tNameE": "Fat Fat Bin",
        "tPerson1": "石宇昂",
        "tPerson1E": "Yuang Shi",
        "sex1": "男",
        "phone1": "15071215160",
        "p1Size": "XXXL",
        "tPerson2": "赵学斌",
        "tPerson2E": "Xuebin Zhao",
        "sex2": "男",
        "phone2": "15207142065",
        "p2Size": "XXL",
        "tPerson3": "郭俊成",
        "tPerson3E": "Juncheng Guo",
        "sex3": "男",
        "phone3": "15071385531",
        "p3Size": "XL"
    },
     {
        "tNumber": "9",
        "school": "西安交通大学",
        "school2": "Xi'an Jiaotong University",
        "type": "会议费",
        "bank": "西安市工商行互助路支行",
        "taxNum": "610103435230200",
        "addr": "陕西省西安市咸宁西路28号西安交通大学",
        "schoolContactName": "沈俞霖",
        "schoolContactPhone": "13452497025",
        "coach": "徐宏喆",
        "coach2": "Hongzhe Xu",
        "coachPhone": "13186115895",
        "coachEmail": "xuhz@xjtu.edu.cn",
        "isCome": "否",
        "cSize": 0,
        "tName": "比特赛特",
        "tNameE": "bitset",
        "tPerson1": "沈俞霖",
        "tPerson1E": "Yulin Shen",
        "sex1": "男",
        "phone1": "13452497025",
        "p1Size": "XXL",
        "tPerson2": "丁聪",
        "tPerson2E": "Cong Ding",
        "sex2": "男",
        "phone2": "13572953130",
        "p2Size": "XL",
        "tPerson3": "刘一凡",
        "tPerson3E": "Yifan Liu",
        "sex3": "男",
        "phone3": "17792480189",
        "p3Size": "XL"
    },
    {
        "tNumber": "10",
        "school": "中国人民大学",
        "school2": "Renmin University of China",
        "type": "竞赛费",
        "bank": "北京工商银行紫竹院支行",
        "taxNum": "12100000400002435L",
        "addr": "北京市海淀区中关村大街59号中国人民大学信息学院",
        "schoolContactName": "朱青",
        "schoolContactPhone": "13641166431",
        "coach": "朱青",
        "coach2": "Zhu Qing",
        "coachPhone": "13641166431",
        "coachEmail": "rucacm@126.com",
        "isCome": "是",
        "cSize": "XL",
        "tName": "金仓_基本法",
        "tNameE": "Basic Law",
        "tPerson1": "汪泽宇",
        "tPerson1E": "Wang Zeyu ",
        "sex1": "男",
        "phone1": "13658135114",
        "p1Size": "M",
        "tPerson2": "何宗炎",
        "tPerson2E": "He Zongyan",
        "sex2": "男",
        "phone2": "18874271219",
        "p2Size": "XXXL",
        "tPerson3": "杨越千",
        "tPerson3E": "Yang Yueqian ",
        "sex3": "男",
        "phone3": "15308427762",
        "p3Size": "L"
    },
     {
        "tNumber": "11",
        "school": "东北林业大学",
        "school2": "Northeast Forestry University",
        "type": "竞赛费",
        "bank": "哈尔滨市香坊区和兴路26号",
        "taxNum": "121000004240062542",
        "addr": "哈尔滨市和兴路26号东北林业大学成栋楼919室",
        "schoolContactName": "陈宇",
        "schoolContactPhone": "15004608100",
        "coach": "陈宇",
        "coach2": "Yu Chen",
        "coachPhone": "15004608100",
        "coachEmail": "nefu_chenyu@163.com",
        "isCome": "是",
        "cSize": "XL",
        "tName": "我能再撩你一下吗",
        "tNameE": "wnzlnyxm",
        "tPerson1": "高鹏",
        "tPerson1E": "peng gao",
        "sex1": "男",
        "phone1": "18845780762",
        "p1Size": "xl",
        "tPerson2": "李俊",
        "tPerson2E": "jun Li",
        "sex2": "男",
        "phone2": "17745163618",
        "p2Size": "xl",
        "tPerson3": "王建中",
        "tPerson3E": "jianzhong wang",
        "sex3": "男",
        "phone3": "18845892687",
        "p3Size": "xl"
    },
     {
        "tNumber": "12",
        "school": "上海大学",
        "school2": "Shanghai University",
        "type": "参赛费",
        "bank": "农行上海共和支行",
        "taxNum": "1231000042502637XE",
        "addr": "上海市宝山区南陈路333号上海大学东区计算机学院811室",
        "schoolContactName": "沈云付",
        "schoolContactPhone": "1804997965",
        "coach": "沈俊",
        "coach2": "Shen Jun",
        "coachPhone": "18918586359",
        "coachEmail": "jshen@t.shu.edu.cn",
        "isCome": "是",
        "cSize": "XL",
        "tName": "狂交原谅色",
        "tNameE": "forgive her",
        "tPerson1": "邵伟",
        "tPerson1E": "Shao Wei",
        "sex1": "男",
        "phone1": "13524142557",
        "p1Size": "XL",
        "tPerson2": "顾伟峰",
        "tPerson2E": "Gu Weifeng",
        "sex2": "男",
        "phone2": "13816652028",
        "p2Size": "XL",
        "tPerson3": "施晟珉",
        "tPerson3E": "Shi Shengmin",
        "sex3": "男",
        "phone3": "18116150131",
        "p3Size": "XL"
    },
     {
        "tNumber": "13",
        "school": "上海大学",
        "school2": "Shanghai University",
        "type": "参赛费",
        "bank": "农行上海共和支行",
        "taxNum": "1231000042502637XE",
        "addr": "上海市宝山区南陈路333号上海大学东区计算机学院811室",
        "schoolContactName": "沈云付",
        "schoolContactPhone": "1804997965",
        "coach": "沈云付",
        "coach2": "Shen Yunfu",
        "coachPhone": "18049979653",
        "coachEmail": "yfshen@mail.shu.edu.cn",
        "isCome": "否",
        "cSize": 0,
        "tName": "时梭者",
        "tNameE": "Time Flyer",
        "tPerson1": "陈之豪",
        "tPerson1E": "Chen Zhihao",
        "sex1": "男",
        "phone1": "18221213946",
        "p1Size": "XL",
        "tPerson2": "陈嘉文",
        "tPerson2E": "Chen Jiawen",
        "sex2": "男",
        "phone2": "13916048393",
        "p2Size": "XL",
        "tPerson3": "姚乾浩",
        "tPerson3E": "Yao Qianhao",
        "sex3": "男",
        "phone3": "18217333260",
        "p3Size": "L"
    },
     {
        "tNumber": "14",
        "school": "华南农业大学",
        "school2": "SCAU",
        "type": "竞赛费",
        "bank": "广州工行五山支行",
        "taxNum": "124400004554165634",
        "addr": "广东省广州市华南农业大学数学与信息学院",
        "schoolContactName": "艾文程",
        "schoolContactPhone": "18320722404",
        "coach": "刘财兴",
        "coach2": "Liu Caixing",
        "coachPhone": "18320722404",
        "coachEmail": "847532971@qq.com",
        "isCome": "是",
        "cSize": "M",
        "tName": "我的那一秒呢",
        "tNameE": "The Lost Second",
        "tPerson1": "艾文程",
        "tPerson1E": "Ai Wencheng",
        "sex1": "男",
        "phone1": "18320722404",
        "p1Size": "XL",
        "tPerson2": "谭志康",
        "tPerson2E": "Tan Zhikang",
        "sex2": "男",
        "phone2": "13427546052",
        "p2Size": "L",
        "tPerson3": "郑卫凯",
        "tPerson3E": "Zheng Weikai",
        "sex3": "男",
        "phone3": "15692400789",
        "p3Size": "L"
    },
    {
        "tNumber": "15",
        "school": "武汉科技大学",
        "school2": "Wuhan University of Science and Technology",
        "type": "会务费",
        "bank": "中行青山支行570357550123\n武汉市青山区和平大道947号027-68862458",
        "taxNum": "12420000441439529L",
        "addr": "湖北省武汉市洪山区黄家湖大学城武汉科技大学黄家湖校区南苑",
        "schoolContactName": "李顺新",
        "schoolContactPhone": "13886012688",
        "coach": "李顺新",
        "coach2": "Li Shunxin",
        "coachPhone": "13886012688",
        "coachEmail": "lishunxin72@163.com",
        "isCome": "是",
        "cSize": "XL",
        "tName": "你们都好熟练",
        "tNameE": "QWQ",
        "tPerson1": "吴锦伟",
        "tPerson1E": "Jinwei Wu",
        "sex1": "男",
        "phone1": "18967356913",
        "p1Size": "XL",
        "tPerson2": "丁攀",
        "tPerson2E": "Pan Ding",
        "sex2": "男",
        "phone2": "15871169437",
        "p2Size": "L",
        "tPerson3": "张军",
        "tPerson3E": "Jun Zhang",
        "sex3": "男",
        "phone3": "13016405760",
        "p3Size": "L"
    },
     {
        "tNumber": "16",
        "school": "北京理工大学",
        "school2": "Bejing Institute Of Technology",
        "type": "会议费",
        "bank": "中国工商银行北京紫竹院支行",
        "taxNum": "110108400009127",
        "addr": "北京市海淀区中关村南大街5号",
        "schoolContactName": "季翔",
        "schoolContactPhone": "13011077766",
        "coach": "陈杰浩",
        "coach2": "ChenJiehao",
        "coachPhone": "13011077766",
        "coachEmail": "929136715@qq.com",
        "isCome": "否",
        "cSize": 0,
        "tName": "巴哈姆特",
        "tNameE": "Bahamut",
        "tPerson1": "季翔",
        "tPerson1E": "JiXiang",
        "sex1": "男",
        "phone1": "13011077766",
        "p1Size": "XXL",
        "tPerson2": "曾贻顺",
        "tPerson2E": "ZengYishun",
        "sex2": "男",
        "phone2": "18811378296",
        "p2Size": "L",
        "tPerson3": "沈云汉",
        "tPerson3E": "ShenYunhan",
        "sex3": "男",
        "phone3": "13683371120",
        "p3Size": "XL"
    },
     {
        "tNumber": "17",
        "school": "北京理工大学",
        "school2": "Bejing Institute Of Technology",
        "type": "会议费",
        "bank": "中国工商银行北京紫竹院支行",
        "taxNum": "110108400009127",
        "addr": "北京市海淀区中关村南大街5号",
        "schoolContactName": "姜天洋",
        "schoolContactPhone": "18210251108",
        "coach": "陈杰浩",
        "coach2": "Chen Jiehao",
        "coachPhone": "13011077766",
        "coachEmail": "bitssacm@163.com",
        "isCome": "是",
        "cSize": "XXL",
        "tName": "从零开始的acm生活",
        "tNameE": "re:starting life in ACM world",
        "tPerson1": "李东",
        "tPerson1E": "LiDong",
        "sex1": "男",
        "phone1": "13552541925",
        "p1Size": "M",
        "tPerson2": "雷云霖",
        "tPerson2E": "LeiYunlin",
        "sex2": "男",
        "phone2": "15801636296",
        "p2Size": "XL",
        "tPerson3": "高硕",
        "tPerson3E": "GaoShuo",
        "sex3": "男",
        "phone3": "15801396957\n",
        "p3Size": "XL"
    },
     {
        "tNumber": "18",
        "school": "吉林大学",
        "school2": "JiLin University",
        "type": "增值普通发票",
        "bank": "长春市前进大街2426号",
        "taxNum": "220104423204064",
        "addr": "长春市前进大街2699号吉林大学计算机学院",
        "schoolContactName": "张黎明",
        "schoolContactPhone": "13604308851",
        "coach": "郭东伟",
        "coach2": "Guo Dongwei",
        "coachPhone": "13009006800",
        "coachEmail": "guodw@jlu.edu.cn",
        "isCome": "是",
        "cSize": "XL",
        "tName": "如果奇迹有颜色",
        "tNameE": "Ac is green",
        "tPerson1": "黄昊天",
        "tPerson1E": "Huang Haotian",
        "sex1": "男",
        "phone1": "15543287143",
        "p1Size": "XL",
        "tPerson2": "陶锴",
        "tPerson2E": "Tao Kai",
        "sex2": "男",
        "phone2": "17843126761",
        "p2Size": "M",
        "tPerson3": "滕云",
        "tPerson3E": "Teng Yun",
        "sex3": "男",
        "phone3": "15764332274",
        "p3Size": "XL"
    },
     {
        "tNumber": "19",
        "school": "苏州大学",
        "school2": "Soochow University",
        "type": "竞赛费",
        "bank": "交通银行股份有限公司苏州苏大支行",
        "taxNum": "123200004660073435",
        "addr": "江苏省苏州市干将东路333号苏州大学本部理工楼101",
        "schoolContactName": "高可攀",
        "schoolContactPhone": "18915222887",
        "coach": "徐汀荣",
        "coach2": "Tingrong Xu",
        "coachPhone": "17715157672",
        "coachEmail": "trxu@suda.edu.cn",
        "isCome": "是",
        "cSize": "L",
        "tName": "你说的对",
        "tNameE": "You Say Right",
        "tPerson1": "王仁杰",
        "tPerson1E": "Renjie Wang",
        "sex1": "男",
        "phone1": "13773289761",
        "p1Size": "L",
        "tPerson2": "祝秀军",
        "tPerson2E": "Xiujun Zhu ",
        "sex2": "男",
        "phone2": "18962150601",
        "p2Size": "L",
        "tPerson3": "郝永昌",
        "tPerson3E": "Yongchang Hao",
        "sex3": "男",
        "phone3": "15110621450",
        "p3Size": "L"
    },
    {
        "tNumber": "20",
        "school": "中南大学",
        "school2": "Central South University",
        "type": "竞赛费",
        "bank": "湖南省长沙市中国银行中南大学支行",
        "taxNum": "430104448805122",
        "addr": "湖南省长沙市岳麓区中南大学南校区南六舍",
        "schoolContactName": "徐戍",
        "schoolContactPhone": "17712069699",
        "coach": "沈海澜",
        "coach2": "Shen Hailan",
        "coachPhone": "13875952018",
        "coachEmail": "csuczl@163.com",
        "isCome": "是",
        "cSize": "XL",
        "tName": "复仇之翼",
        "tNameE": "The Wing of Vengeance",
        "tPerson1": "徐戍",
        "tPerson1E": "Xu Shu",
        "sex1": "男",
        "phone1": "17712069699",
        "p1Size": "L",
        "tPerson2": "卢铭威",
        "tPerson2E": "Lu Mingwei",
        "sex2": "男",
        "phone2": "15616162767",
        "p2Size": "L",
        "tPerson3": "石文斌",
        "tPerson3E": "Shi Wenbin",
        "sex3": "男",
        "phone3": "18273135372",
        "p3Size": "M"
    },
     {
        "tNumber": "21",
        "school": "陕西师范大学",
        "school2": "Shaanxi Normal University",
        "type": "会议费",
        "bank": "中国银行师大路分行",
        "taxNum": "61011343523253x",
        "addr": "陕西省西安市长安区陕西师范大学",
        "schoolContactName": "黄凌宇",
        "schoolContactPhone": "13384957139\n",
        "coach": "王涛",
        "coach2": "Tao Wang",
        "coachPhone": "17792038063",
        "coachEmail": "snnu_acm@163.com",
        "isCome": "是",
        "cSize": "XL",
        "tName": "不听不听，无甲沙鹰",
        "tNameE": "P90 Rush B",
        "tPerson1": "袁敏杰",
        "tPerson1E": "Minjie Yan",
        "sex1": "男",
        "phone1": "15771930250",
        "p1Size": "L",
        "tPerson2": "任加祥",
        "tPerson2E": "Jiaxiang Ren",
        "sex2": "男",
        "phone2": "15619273803",
        "p2Size": "XL",
        "tPerson3": "董逸晨",
        "tPerson3E": "Yichen Dong",
        "sex3": "男",
        "phone3": "15188898698",
        "p3Size": "XL"
    },
    {
        "tNumber": "22",
        "school": "中北大学",
        "school2": "North University of China ",
        "type": "竞赛费",
        "bank": "太原市工行迎新街支行",
        "taxNum": "12140000405747348X",
        "addr": "山西省太原市尖草坪区中北大学ACM实验室",
        "schoolContactName": "潘广贞",
        "schoolContactPhone": "13934621825",
        "coach": "潘广贞",
        "coach2": "Guangzhen Pan",
        "coachPhone": "13934621825",
        "coachEmail": "nuc_acm@qq.com",
        "isCome": "是",
        "cSize": "XL",
        "tName": "越过顶峰",
        "tNameE": "beyond-T",
        "tPerson1": "张明星",
        "tPerson1E": "Mingxing Zhang",
        "sex1": "男",
        "phone1": "18234189836",
        "p1Size": "XL",
        "tPerson2": "梁潇",
        "tPerson2E": "liangxiao",
        "sex2": "男",
        "phone2": "13327514577",
        "p2Size": "xl",
        "tPerson3": "郭星刚\n",
        "tPerson3E": "Xinggang Guo\n",
        "sex3": "男",
        "phone3": "18234167390",
        "p3Size": "XL"
    },
   {
        "tNumber": "23",
        "school": "长春工业大学",
        "school2": "Changchun  University of Technology",
        "type": "竞赛费",
        "bank": "建行长春高新技术产业开发区支行",
        "taxNum": "122200004127567019",
        "addr": "吉林省长春市延安大街2055号",
        "schoolContactName": "周丽娟",
        "schoolContactPhone": "18543196868",
        "coach": "周丽娟",
        "coach2": "Lijuan Zhou",
        "coachPhone": "18543196868",
        "coachEmail": "1690536767@qq.com",
        "isCome": "是",
        "cSize": "XL",
        "tName": "乌鸦坐飞机",
        "tNameE": "Winner Winner,Chicken Dinner",
        "tPerson1": "任义",
        "tPerson1E": "Yu Pei",
        "sex1": "男",
        "phone1": "15526655223",
        "p1Size": "XL",
        "tPerson2": "陈杰",
        "tPerson2E": "J C",
        "sex2": "男",
        "phone2": "17757066702",
        "p2Size": "L",
        "tPerson3": "王元",
        "tPerson3E": "Yuan Wang",
        "sex3": "男",
        "phone3": "15584427369",
        "p3Size": "L"
    },
     {
        "tNumber": "24",
        "school": "南京大学",
        "school2": "Nanjing University",
        "type": "参赛费、会议费均可",
        "bank": "工行汉口路支行",
        "taxNum": "12100000466007458m",
        "addr": "江苏省南京市栖霞区仙林大道163号南京大学计算机科学与技术系",
        "schoolContactName": "马骏",
        "schoolContactPhone": "18951991733",
        "coach": "马骏",
        "coach2": "MA Jun",
        "coachPhone": "18951991733",
        "coachEmail": "majun@",
        "isCome": "是",
        "cSize": "XL",
        "tName": "八阿哥缔造者",
        "tNameE": "BugCreators",
        "tPerson1": "尚柯宇",
        "tPerson1E": "SHANG Keyu",
        "sex1": "男",
        "phone1": "13236552278",
        "p1Size": "XL",
        "tPerson2": "王冬杨",
        "tPerson2E": "WANG Dongyang",
        "sex2": "男",
        "phone2": "18851822230",
        "p2Size": "XL",
        "tPerson3": "童正阳",
        "tPerson3E": "TONG Zhengyang",
        "sex3": "男",
        "phone3": "15152626489",
        "p3Size": "XL"
    },
     {
        "tNumber": "25",
        "school": "哈尔滨工程大学",
        "school2": "Harbin Engineering University",
        "type": "会务费",
        "bank": "中国工商银行股份有限公司哈尔滨宣桥支行",
        "taxNum": "12100000424006211L",
        "addr": "哈尔滨市南岗区南通大街145号哈尔滨工程大学21号楼573室",
        "schoolContactName": "王心亮",
        "schoolContactPhone": "15620001121",
        "coach": "国林",
        "coach2": "Lin Guo",
        "coachPhone": "13936137218",
        "coachEmail": "guolin@hrbeu.edu.cn",
        "isCome": "是",
        "cSize": "XXL",
        "tName": "我是为了你的熊",
        "tNameE": "for your bear",
        "tPerson1": "王心亮",
        "tPerson1E": "Xinliang Wang",
        "sex1": "男",
        "phone1": "15620001121",
        "p1Size": "XL",
        "tPerson2": "冯德帆",
        "tPerson2E": "Defan Feng",
        "sex2": "男",
        "phone2": "17745169337",
        "p2Size": "XXL",
        "tPerson3": "徐荣琛",
        "tPerson3E": "Rongchen Xu",
        "sex3": "男",
        "phone3": "17745169528",
        "p3Size": "XXL"
    },
     {
        "tNumber": "26",
        "school": "哈尔滨工程大学",
        "school2": "Harbin Engineering University",
        "type": "会务费",
        "bank": "中国工商银行股份有限公司哈尔滨宣桥支行",
        "taxNum": "12100000424006211L",
        "addr": "哈尔滨市南岗区南通大街145号哈尔滨工程大学21号楼573室",
        "schoolContactName": "王心亮",
        "schoolContactPhone": "15620001121",
        "coach": "国林",
        "coach2": "Lin Guo",
        "coachPhone": "13936137218",
        "coachEmail": "guolin@hrbeu.edu.cn",
        "isCome": "是",
        "cSize": "XXL",
        "tName": "大家好今天是星期日",
        "tNameE": "Sunday today",
        "tPerson1": "卢思旭",
        "tPerson1E": "Sixu Lu",
        "sex1": "女",
        "phone1": "18804638728",
        "p1Size": "S",
        "tPerson2": "翁银兵",
        "tPerson2E": "Yinbing Weng",
        "sex2": "女",
        "phone2": "18846425113",
        "p2Size": "M",
        "tPerson3": "张慧",
        "tPerson3E": "Hui Zhang",
        "sex3": "女",
        "phone3": "13251510620",
        "p3Size": "M"
    },
     {
        "tNumber": "27",
        "school": "大连海事大学",
        "school2": "Dalian Maritime University",
        "type": "会务费",
        "bank": "中国银行大连高新技术园区支行",
        "taxNum": "12100000422436461A",
        "addr": "辽宁省大连市大连海事大学邮件收发管理服务中心",
        "schoolContactName": "牟牧云",
        "schoolContactPhone": "18042654006",
        "coach": "谢益武",
        "coach2": "Yiwu Xie",
        "coachPhone": "13084104958",
        "coachEmail": "xyw1965@163.com",
        "isCome": "是",
        "cSize": "L",
        "tName": "打铁去",
        "tNameE": "datiequ",
        "tPerson1": "叶骁寒",
        "tPerson1E": "Xiaohan Ye",
        "sex1": "男",
        "phone1": "18742520576",
        "p1Size": "L",
        "tPerson2": "王园园",
        "tPerson2E": "Yuanyuan Wang",
        "sex2": "女",
        "phone2": "18742519502",
        "p2Size": "S",
        "tPerson3": "蔡澄奕",
        "tPerson3E": "Chengyi Cai",
        "sex3": "女",
        "phone3": "18742521280",
        "p3Size": "S"
    },
   {
        "tNumber": "28",
        "school": "深圳大学",
        "school2": "SZU",
        "type": "竞赛费",
        "bank": "深圳市南山区南海大道3688号深圳大学",
        "taxNum": "124403004557453164",
        "addr": "深圳市南山区南海大道3688号深圳大学冬筑319",
        "schoolContactName": "周园洲",
        "schoolContactPhone": "13760194383",
        "coach": "张小健",
        "coach2": "zxj",
        "coachPhone": "13622399863",
        "coachEmail": "1014728601@qq.com",
        "isCome": "否",
        "cSize": 0,
        "tName": "星之海",
        "tNameE": "SZU_ZXH",
        "tPerson1": "肖亮",
        "tPerson1E": "xl",
        "sex1": "男",
        "phone1": "13168059266",
        "p1Size": "XL",
        "tPerson2": "周园洲",
        "tPerson2E": "zyz",
        "sex2": "男",
        "phone2": "13760194383",
        "p2Size": "XL",
        "tPerson3": "胡杰仁",
        "tPerson3E": "hjr",
        "sex3": "男",
        "phone3": "13798283341",
        "p3Size": "L"
    },
    {
        "tNumber": "29",
        "school": "西安电子科技大学",
        "school2": "Xidian University",
        "type": "竞赛费",
        "bank": "交通银行西安光华路支行 西安市太白南路2号",
        "taxNum": "121000004352307294",
        "addr": "陕西省西安市西沣路兴隆段266号 软件学院",
        "schoolContactName": "张淑平",
        "schoolContactPhone": "13572056871",
        "coach": "张淑平",
        "coach2": "Shuping Zhang",
        "coachPhone": "13572056871",
        "coachEmail": "zhangshuping2002@163.com",
        "isCome": "否",
        "cSize": 0,
        "tName": "喂自己袋烟",
        "tNameE": "Fog Fantasy",
        "tPerson1": "欧阳健文",
        "tPerson1E": "Ouyang Jianwen",
        "sex1": "男",
        "phone1": "13013063086",
        "p1Size": "L",
        "tPerson2": "朱仁博",
        "tPerson2E": "Zhu Renbo",
        "sex2": "男",
        "phone2": "13032978342",
        "p2Size": "XXL",
        "tPerson3": "韦润民",
        "tPerson3E": "Wei Runmin",
        "sex3": "男",
        "phone3": "13227855005",
        "p3Size": "L"
    },
    {
        "tNumber": "30",
        "school": "南京邮电大学",
        "school2": "Nanjing University of Posts and Telecommunications",
        "type": "竞赛费",
        "bank": "工商银行察哈尔路支行",
        "taxNum": "123200004260908590",
        "addr": "南京市亚东新城区文苑路9号，南京邮电大学计算机学院842信箱",
        "schoolContactName": "陈志",
        "schoolContactPhone": "13813930027",
        "coach": "陈志、章韵",
        "coach2": "Chen Zhi, Zhang Yun",
        "coachPhone": "13813930027",
        "coachEmail": "chenz@njupt.edu.cn",
        "isCome": "是（有一位领队/教练老师参加：章韵）",
        "cSize": "XXL",
        "tName": "拯救世界",
        "tNameE": "NJUPT_Goforworld",
        "tPerson1": "邹子昕",
        "tPerson1E": "Zou Zixin",
        "sex1": "男",
        "phone1": "18705175960",
        "p1Size": "XL",
        "tPerson2": "张正昊",
        "tPerson2E": "Zhang Zhenghao",
        "sex2": "男",
        "phone2": "18066110016",
        "p2Size": "L",
        "tPerson3": "陈志远",
        "tPerson3E": "Chen Zhiyuan",
        "sex3": "男",
        "phone3": "18251931070",
        "p3Size": "L"
    },
     {
        "tNumber": "31",
        "school": "华东交通大学",
        "school2": "East China Jiaotong University",
        "type": "竞赛费",
        "bank": "建行南昌市华东交大支行",
        "taxNum": "12360000491018175R",
        "addr": "江西省南昌市青山湖区华东交通大学北区",
        "schoolContactName": "梅伟民",
        "schoolContactPhone": "15180156243",
        "coach": "周娟",
        "coach2": "Juan Zhou",
        "coachPhone": "13970951602",
        "coachEmail": "coachzhoujuan@163.com",
        "isCome": "是",
        "cSize": "L",
        "tName": "旷课一星期",
        "tNameE": "Absenteeism a week",
        "tPerson1": "梅伟民",
        "tPerson1E": "Weimin Mei",
        "sex1": "男",
        "phone1": "15180156243",
        "p1Size": "  XL",
        "tPerson2": "廖鑫颖",
        "tPerson2E": "Xinying Liao",
        "sex2": "  男",
        "phone2": "15279787250",
        "p2Size": "L",
        "tPerson3": "余志旺",
        "tPerson3E": "Zhiwang Yu",
        "sex3": "男",
        "phone3": "15797694236",
        "p3Size": "L"
    },
     {
        "tNumber": "32",
        "school": "浙江大学宁波理工学院",
        "school2": "Ningbo Institute of Technology,ZJU",
        "type": "竞赛费",
        "bank": "农行宁波天一支行",
        "taxNum": "12330200730164787W",
        "addr": "浙江省宁波市鄞州区学府路1号",
        "schoolContactName": "郭新友",
        "schoolContactPhone": "13867876076",
        "coach": "郭新友",
        "coach2": "Xinyou Guo",
        "coachPhone": "13867876076",
        "coachEmail": "guoxinyou@foxmail.com",
        "isCome": "是",
        "cSize": "XXL",
        "tName": "探险小分队",
        "tNameE": "Adventure Team",
        "tPerson1": "许嵘",
        "tPerson1E": "Rong Xu",
        "sex1": "男",
        "phone1": "17858936055",
        "p1Size": "XL",
        "tPerson2": "包敬恒",
        "tPerson2E": "Jingheng Bao",
        "sex2": "男",
        "phone2": "17858937546",
        "p2Size": "XXL",
        "tPerson3": "施润丰",
        "tPerson3E": "Runfeng Shi",
        "sex3": "男",
        "phone3": "18267267873",
        "p3Size": "XL"
    },
     {
        "tNumber": "33",
        "school": "西安理工大学",
        "school2": "Xi'an University of Technology",
        "type": "参赛费",
        "bank": "中国银行西安金花南路支行",
        "taxNum": "61010343523042X",
        "addr": "陕西省西安市金花南路5号西安理工大学计算机科学与工程学院",
        "schoolContactName": "赵金伟",
        "schoolContactPhone": "13891436823",
        "coach": "赵金伟",
        "coach2": "Jinwei Zhao",
        "coachPhone": "13891436823",
        "coachEmail": "zhaojinwei@xaut.edu.cn",
        "isCome": "是",
        "cSize": "XXXL",
        "tName": "上升",
        "tNameE": "Up",
        "tPerson1": "朱文星",
        "tPerson1E": "Wenxing Zhu",
        "sex1": "男",
        "phone1": "15604996072",
        "p1Size": "XXL",
        "tPerson2": "王学宇",
        "tPerson2E": "Xueyu Wang",
        "sex2": "男",
        "phone2": "15029920267",
        "p2Size": "M",
        "tPerson3": "王逸含",
        "tPerson3E": "Yihan Wang",
        "sex3": "男",
        "phone3": "18329480771",
        "p3Size": "L"
    },
     {
        "tNumber": "34",
        "school": "浙江大学城市学院",
        "school2": "Zhejiang University City College",
        "type": "参赛费",
        "bank": "中国建设银行杭州文晖支行营业部",
        "taxNum": "12330100470090282R",
        "addr": "杭州市拱墅区湖州街50号浙江大学城市学院计算分院",
        "schoolContactName": "柯海丰",
        "schoolContactPhone": "13355788250",
        "coach": "柯海丰",
        "coach2": "Ke Haifeng",
        "coachPhone": "13355788250",
        "coachEmail": "kehf@zucc.edu.cn",
        "isCome": "是",
        "cSize": "XL",
        "tName": "Paprika",
        "tNameE": "Paprika",
        "tPerson1": "陈哲凡",
        "tPerson1E": "Chen Zhefan",
        "sex1": "男",
        "phone1": "13685752780",
        "p1Size": "L",
        "tPerson2": "陈士俊",
        "tPerson2E": "Chen Shijun",
        "sex2": "男",
        "phone2": "15988166896",
        "p2Size": "XL",
        "tPerson3": "吴成铭",
        "tPerson3E": "Wu Chenming",
        "sex3": "男",
        "phone3": "13656535285",
        "p3Size": "XL"
    },
    {
        "tNumber": "35",
        "school": "广东工业大学",
        "school2": "Guangdong University of Technology",
        "type": "竞赛费\n",
        "bank": "广州市东风东路729号",
        "taxNum": "12440000455860226X",
        "addr": "广州越秀区水荫路34号大院31号802",
        "schoolContactName": "孙宣东",
        "schoolContactPhone": "18664541866",
        "coach": "孙宣东",
        "coach2": "Sun Xuandong",
        "coachPhone": "18664541866",
        "coachEmail": "36430372@qq.com",
        "isCome": "是",
        "cSize": "XXL",
        "tName": "穷游中国",
        "tNameE": "Travel_Poorly",
        "tPerson1": "唐铭锴",
        "tPerson1E": "Tang Mingkai",
        "sex1": "男",
        "phone1": "13189639312",
        "p1Size": "XL",
        "tPerson2": "林渲竺",
        "tPerson2E": "Lin Xuanzhu",
        "sex2": "男",
        "phone2": "13631475257",
        "p2Size": "XL",
        "tPerson3": "杨富强",
        "tPerson3E": "Yang Fuqiang",
        "sex3": "男",
        "phone3": "13192661921",
        "p3Size": "L"
    },
     {
        "tNumber": "36",
        "school": "华中科技大学",
        "school2": "Huazhong University of Science and Technology",
        "type": "会务费",
        "bank": "中国建设银行武汉喻家山支行",
        "taxNum": "12100000441626842D",
        "addr": "湖北省武汉市洪山区珞瑜路1037号华中科技大学创新研究院905",
        "schoolContactName": "何琨",
        "schoolContactPhone": "13006163312",
        "coach": "何琨",
        "coach2": "He Kun",
        "coachPhone": "13364307093",
        "coachEmail": "351762385@qq.com",
        "isCome": "否",
        "cSize": 0,
        "tName": "华科附属幼儿园",
        "tNameE": "HUST Affiliated Kindergarten",
        "tPerson1": "张嘉辉",
        "tPerson1E": "Jiahui Zhang",
        "sex1": "男",
        "phone1": "17371266465",
        "p1Size": "XL",
        "tPerson2": "陈威宇",
        "tPerson2E": "Weiyu Chen",
        "sex2": "男",
        "phone2": "17371266259",
        "p2Size": "M",
        "tPerson3": "马思源",
        "tPerson3E": "Siyuan Ma",
        "sex3": "男",
        "phone3": "15927217186",
        "p3Size": "M"
    },
    {
        "tNumber": "37",
        "school": "北京交通大学",
        "school2": "Beijing Jiaotong University",
        "type": "竞赛费",
        "bank": "中国工商银行北京新街口支行",
        "taxNum": "1210000040088209X1",
        "addr": "北京交通大学计算机工程系",
        "schoolContactName": "黄华",
        "schoolContactPhone": "13691546808",
        "coach": "黄华",
        "coach2": "Huang Hua",
        "coachPhone": "13691546808",
        "coachEmail": "hhua@bjtu.edu.cn",
        "isCome": "是",
        "cSize": "XL",
        "tName": "猜歌群",
        "tNameE": "GuessSongs",
        "tPerson1": "何卫锋",
        "tPerson1E": "HE WeiFeng",
        "sex1": "男",
        "phone1": "18801269623",
        "p1Size": "L",
        "tPerson2": "郑黎明",
        "tPerson2E": "ZHENG LiMing",
        "sex2": "男",
        "phone2": "18401606113",
        "p2Size": "L",
        "tPerson3": "王天舒",
        "tPerson3E": "WANG TianShu",
        "sex3": "男",
        "phone3": "18310379839",
        "p3Size": "XXL"
    },
     {
        "tNumber": "38",
        "school": "中南大学",
        "school2": "Central South University",
        "type": "竞赛费",
        "bank": "湖南省长沙市中国银行中南大学支行",
        "taxNum": "430104448805122",
        "addr": "湖南省长沙市岳麓区中南大学南校区南六舍",
        "schoolContactName": "徐戍",
        "schoolContactPhone": "17712069699",
        "coach": "沈海澜",
        "coach2": "Shen Hailan",
        "coachPhone": "13875952018",
        "coachEmail": "csuczl@163.com",
        "isCome": "是",
        "cSize": "XL",
        "tName": "复仇之翼",
        "tNameE": "The Wing of Vengeance",
        "tPerson1": "徐戍",
        "tPerson1E": "Xu Shu",
        "sex1": "男",
        "phone1": "17712069699",
        "p1Size": "L",
        "tPerson2": "卢铭威",
        "tPerson2E": "Lu Mingwei",
        "sex2": "男",
        "phone2": "15616162767",
        "p2Size": "L",
        "tPerson3": "石文斌",
        "tPerson3E": "Shi Wenbin",
        "sex3": "男",
        "phone3": "18273135372",
        "p3Size": "M"
    },
   {
        "tNumber": "39",
        "school": "北京航空航天大学",
        "school2": "Beihang University",
        "type": "会议费",
        "bank": "中国工商银行北京东升路支行",
        "taxNum": "12100000400011227Y",
        "addr": "北京市海淀区学院路37号",
        "schoolContactName": "梁明阳",
        "schoolContactPhone": "13146014364",
        "coach": "梁明阳",
        "coach2": "Mingyang Liang",
        "coachPhone": "13021227021",
        "coachEmail": "yicotn@qq.com",
        "isCome": "否",
        "cSize": 0,
        "tName": "上头欢乐送",
        "tNameE": "TVCR",
        "tPerson1": "王意如",
        "tPerson1E": "Yiru Wang",
        "sex1": "男",
        "phone1": "13121269982",
        "p1Size": "XXL",
        "tPerson2": "张乾宇",
        "tPerson2E": "Qianyu Zhang",
        "sex2": "男",
        "phone2": "18810717855",
        "p2Size": "XXL",
        "tPerson3": "郭镕昊",
        "tPerson3E": "Ronghao Guo",
        "sex3": "男",
        "phone3": "15652588575",
        "p3Size": "XXL"
    },
     {
        "tNumber": "40",
        "school": "华北电力大学",
        "school2": "North China Electric Power University",
        "type": "会议费（个人发票）",
        "bank": "自费",
        "taxNum": "自费",
        "addr": "北京市昌平区回龙观北农路2号华北电力大学",
        "schoolContactName": "周鹏威",
        "schoolContactPhone": "15010989128",
        "coach": "马炜",
        "coach2": "Ma Wei",
        "coachPhone": "13391928978",
        "coachEmail": "335131843@qq.com",
        "isCome": "否",
        "cSize": 0,
        "tName": "湖人队",
        "tNameE": "LAKERS",
        "tPerson1": "陈太钦",
        "tPerson1E": "Chen Taiqin",
        "sex1": "男",
        "phone1": "18976205457",
        "p1Size": "3XXX",
        "tPerson2": "李孔源",
        "tPerson2E": "Li Kongyuan",
        "sex2": "男",
        "phone2": "15626309728",
        "p2Size": "L",
        "tPerson3": "左乾旭",
        "tPerson3E": "Zuo Qianxu",
        "sex3": "男",
        "phone3": "18810796597",
        "p3Size": "L"
    },
     {
        "tNumber": "41",
        "school": "西安理工大学",
        "school2": "Xi'an University of Technology",
        "type": "参赛费",
        "bank": "中国银行西安金花南路支行",
        "taxNum": "61010343523042X",
        "addr": "陕西省西安市金花南路5号西安理工大学计算机科学与工程学院",
        "schoolContactName": "赵金伟",
        "schoolContactPhone": "13891436823",
        "coach": "赵金伟",
        "coach2": "Jinwei Zhao",
        "coachPhone": "13891436823",
        "coachEmail": "zhaojinwei@xaut.edu.cn",
        "isCome": "是",
        "cSize": "XXXL",
        "tName": "上升",
        "tNameE": "Up",
        "tPerson1": "朱文星",
        "tPerson1E": "Wenxing Zhu",
        "sex1": "男",
        "phone1": "15604996072",
        "p1Size": "XXL",
        "tPerson2": "王学宇",
        "tPerson2E": "Xueyu Wang",
        "sex2": "男",
        "phone2": "15029920267",
        "p2Size": "M",
        "tPerson3": "王逸含",
        "tPerson3E": "Yihan Wang",
        "sex3": "男",
        "phone3": "18329480771\n",
        "p3Size": "L"
    },
    {
        "tNumber": "42",
        "school": "江西中医药大学",
        "school2": "Jiangxi University of traditional Chinese Medicine",
        "type": "参赛费",
        "bank": "江西省南昌市农行青云谱支行新苑分理处",
        "taxNum": "123600004910159513\n",
        "addr": "江西省南昌市湾里区梅岭大道818号江西中医药大学",
        "schoolContactName": "朱彦陈",
        "schoolContactPhone": "18170866805",
        "coach": "朱彦陈",
        "coach2": "Zhu Yanchen ",
        "coachPhone": "18170866805",
        "coachEmail": "80226700@qq.com",
        "isCome": "是",
        "cSize": "XL",
        "tName": "岐黄拓荒者",
        "tNameE": "Qi Huang Tuo Huang Zhe",
        "tPerson1": "毛政翔",
        "tPerson1E": "Mao Zhengxiang",
        "sex1": "男",
        "phone1": "18728753780",
        "p1Size": "S",
        "tPerson2": "张北清",
        "tPerson2E": "Zhang Beiqing",
        "sex2": "男",
        "phone2": "18807049124",
        "p2Size": "M",
        "tPerson3": "但扬杰",
        "tPerson3E": "Dan Yangjie",
        "sex3": "男",
        "phone3": "13677089075",
        "p3Size": "M"
    },
     {
        "tNumber": "43",
        "school": "武汉大学",
        "school2": "Wuhan University",
        "type": "竞赛费",
        "bank": "中国银行股份有限公司武汉珞珈山支行",
        "taxNum": "鄂地税字12100000707137123P号",
        "addr": "武汉市洪山区武汉大学信息学部学生8舍",
        "schoolContactName": "郭松",
        "schoolContactPhone": "13277050260",
        "coach": "董文永",
        "coach2": "Dong Wenyong",
        "coachPhone": "13628692722",
        "coachEmail": "dwy@whu.edu.cn",
        "isCome": "是",
        "cSize": "XL",
        "tName": "魔极客",
        "tNameE": "Mogic",
        "tPerson1": "甄牧放",
        "tPerson1E": "Zhen Mufang",
        "sex1": "男",
        "phone1": "15267529594",
        "p1Size": "XL",
        "tPerson2": "荣大中",
        "tPerson2E": "Rong Dazhong",
        "sex2": "男",
        "phone2": "15927237774",
        "p2Size": "XL",
        "tPerson3": "陶怡平",
        "tPerson3E": "Tao Yiping",
        "sex3": "男",
        "phone3": "15549446910",
        "p3Size": "XL"
    },
     {
        "tNumber": "44",
        "school": "河南工业大学",
        "school2": "Henan University of Technology",
        "type": "参赛费",
        "bank": "中国农业银行郑州中原支行",
        "taxNum": "410102415806196",
        "addr": "河南省郑州市高新技术开发区莲花街河南工业大学信息学院",
        "schoolContactName": "程立",
        "schoolContactPhone": "18623716956",
        "coach": "杨卫东",
        "coach2": "Weidong Yang",
        "coachPhone": "18623716956",
        "coachEmail": "12270373@qq.com",
        "isCome": "否",
        "cSize": 0,
        "tName": "风继续吹",
        "tNameE": "Ease my mind",
        "tPerson1": "张宇",
        "tPerson1E": "Zhang Yu",
        "sex1": "男",
        "phone1": "13253316714",
        "p1Size": "XL",
        "tPerson2": "冯婧涛",
        "tPerson2E": "Feng Jingtao",
        "sex2": "女",
        "phone2": "17736030117\n",
        "p2Size": "XL",
        "tPerson3": "鱼坤",
        "tPerson3E": "Yu Kun",
        "sex3": "男",
        "phone3": "18638765423",
        "p3Size": "M"
    },
    {
        "tNumber": "45",
        "school": "山东大学",
        "school2": "ShanDong University",
        "type": "竞赛费",
        "bank": "中国银行济南历城支行",
        "taxNum": "12100000495570303U",
        "addr": "山东省青岛市即墨市鳌山卫镇滨海路72号山东大学青岛校区计算机学院",
        "schoolContactName": "俞旭铮",
        "schoolContactPhone": "17854160268",
        "coach": "何萌",
        "coach2": "Meng He",
        "coachPhone": "15098966858",
        "coachEmail": "sduacm@126.com",
        "isCome": "是",
        "cSize": "XXL",
        "tName": "吃蛋挞",
        "tNameE": "SDU_Chitanda",
        "tPerson1": "焦方锴",
        "tPerson1E": "Fangkai Jiao",
        "sex1": "男",
        "phone1": "17864154896",
        "p1Size": "XXL",
        "tPerson2": "林信然",
        "tPerson2E": "Xinran Lin",
        "sex2": "男",
        "phone2": "17854215050",
        "p2Size": "XXL",
        "tPerson3": "吉学博",
        "tPerson3E": "Xuebo Ji",
        "sex3": "男",
        "phone3": "17854160266",
        "p3Size": "XXL"
    },
    {
        "tNumber": "46",
        "school": "大连理工大学",
        "school2": "Dalian University of Technology",
        "type": "竞赛费",
        "bank": "中国建设银行大连市栾金支行",
        "taxNum": "12100000422436090K ",
        "addr": "辽宁省大连市金州区图强街321号大连理工大学开发区校区",
        "schoolContactName": "李煜峰",
        "schoolContactPhone": "18537587299",
        "coach": "路慧",
        "coach2": "Lu Hui",
        "coachPhone": "15941150206",
        "coachEmail": "luhui@dlut.edu.cn",
        "isCome": "否",
        "cSize": 0,
        "tName": "对不队",
        "tNameE": "right or not",
        "tPerson1": "杨飞",
        "tPerson1E": "Fei Yang",
        "sex1": "男",
        "phone1": "18742592529",
        "p1Size": "L",
        "tPerson2": "高凯",
        "tPerson2E": "Kai Gao",
        "sex2": "男",
        "phone2": "18742585896",
        "p2Size": "L",
        "tPerson3": "李煜峰",
        "tPerson3E": "Yufeng Li",
        "sex3": "男",
        "phone3": "18537587299",
        "p3Size": "L"
    },
   {
        "tNumber": "47",
        "school": "北京大学",
        "school2": "Peking University",
        "type": "竞赛费",
        "bank": "工行北京海淀西区支行",
        "taxNum": "110108400002259",
        "addr": "北京大学理科5号楼516S",
        "schoolContactName": "罗国杰",
        "schoolContactPhone": "13928603535",
        "coach": "罗国杰",
        "coach2": "Guojie Luo",
        "coachPhone": "13928603535",
        "coachEmail": "gluo@pku.edu.cn",
        "isCome": "否",
        "cSize": 0,
        "tName": "谬误之扉",
        "tNameE": "Wrong Door",
        "tPerson1": "孙奕灿",
        "tPerson1E": "Yican Sun",
        "sex1": "男",
        "phone1": "13777335996",
        "p1Size": "L",
        "tPerson2": "冯哲",
        "tPerson2E": "Zhe Feng",
        "sex2": "男",
        "phone2": "15314790935",
        "p2Size": "L",
        "tPerson3": "陶渊政",
        "tPerson3E": "Yuanzheng Tao",
        "sex3": "男",
        "phone3": "18811700129",
        "p3Size": "XL"
    },
    {
        "tNumber": "48",
        "school": "北京大学",
        "school2": "Peking University",
        "type": "竞赛费",
        "bank": "工行北京海淀西区支行",
        "taxNum": "110108400002259",
        "addr": "北京大学理科5号楼516S",
        "schoolContactName": "罗国杰",
        "schoolContactPhone": "13928603535",
        "coach": "黎才华",
        "coach2": "Caihua Li",
        "coachPhone": "15650709586",
        "coachEmail": "peterli@pku.edu.cn",
        "isCome": "否",
        "cSize": 0,
        "tName": "全给党",
        "tNameE": "Check it out",
        "tPerson1": "吉如一",
        "tPerson1E": "Ruyi Ji",
        "sex1": "男",
        "phone1": "15652657399",
        "p1Size": "XL",
        "tPerson2": "丁力煌",
        "tPerson2E": "Lihuang Ding",
        "sex2": "男",
        "phone2": "15850528967",
        "p2Size": "XL",
        "tPerson3": "洪华敦",
        "tPerson3E": "Huadun Hong",
        "sex3": "男",
        "phone3": "15925849378",
        "p3Size": "XXL"
    },
     {
        "tNumber": "49",
        "school": "北京大学",
        "school2": "Peking University",
        "type": "竞赛费",
        "bank": "工行北京海淀西区支行",
        "taxNum": "110108400002259",
        "addr": "北京大学理科5号楼516S",
        "schoolContactName": "罗国杰",
        "schoolContactPhone": "13928603535",
        "coach": "倪星宇",
        "coach2": "Xingyu Ni",
        "coachPhone": "18855310186",
        "coachEmail": "nixy@qq.com",
        "isCome": "是",
        "cSize": "L",
        "tName": "咕咕咕",
        "tNameE": "Cuckoo",
        "tPerson1": "章玄润",
        "tPerson1E": "Xuanrun Zhang",
        "sex1": "男",
        "phone1": "15733121287",
        "p1Size": "L",
        "tPerson2": "陈牧歌",
        "tPerson2E": "Muge Chen",
        "sex2": "男",
        "phone2": "18810810184",
        "p2Size": "L",
        "tPerson3": "林泽辉",
        "tPerson3E": "Zehui Lin",
        "sex3": "男",
        "phone3": "13316230265",
        "p3Size": "XL"
    },
    {
        "tNumber": "50",
        "school": "东南大学",
        "school2": "Southeast University",
        "type": "参赛费",
        "bank": "建设银行南京市四牌楼支行",
        "taxNum": "12100000466006770Q\n",
        "addr": "江苏省南京市江宁区秣陵街道东南大学九龙湖校区计算机楼156",
        "schoolContactName": "朱鑫",
        "schoolContactPhone": "13758522886",
        "coach": "倪庆剑",
        "coach2": "Qingjian Ni",
        "coachPhone": "13851798466",
        "coachEmail": "niqingjian@gmail.com",
        "isCome": "否",
        "cSize": 0,
        "tName": "是什么呢",
        "tNameE": "NooWA",
        "tPerson1": "施超敏",
        "tPerson1E": "Chaomin Shi",
        "sex1": "男",
        "phone1": "15151862136",
        "p1Size": "XXL",
        "tPerson2": "袁歆雨",
        "tPerson2E": "Xinyu Yuan",
        "sex2": "男",
        "phone2": "15261419189",
        "p2Size": "XXL",
        "tPerson3": "何靖远",
        "tPerson3E": "Jingyuan He",
        "sex3": "男",
        "phone3": "13222726566",
        "p3Size": "XXL"
    },
     {
        "tNumber": "51",
        "school": "福州大学",
        "school2": "Fuzhou university",
        "type": "会议费",
        "bank": "福州省福州地区大学城学院路2号(旗山校区)福州市工行凤凰支行",
        "taxNum": "12350000488002092Y",
        "addr": "福建省福州市闽侯县福州大学旗山校区#59 523",
        "schoolContactName": "卓一帆",
        "schoolContactPhone": "18030051356",
        "coach": "傅仰耿",
        "coach2": "Fu Yanggeng",
        "coachPhone": "18065162651",
        "coachEmail": "ygfu@qq.com",
        "isCome": "是",
        "cSize": "XXL",
        "tName": "百变怪",
        "tNameE": "Ditto",
        "tPerson1": "邹鹏",
        "tPerson1E": "Zou Peng",
        "sex1": "男",
        "phone1": "18850149426",
        "p1Size": "L",
        "tPerson2": "陈铭钦",
        "tPerson2E": "Chen Mingqin",
        "sex2": "男",
        "phone2": "18650394171",
        "p2Size": "L",
        "tPerson3": "郑浩晖",
        "tPerson3E": "Zheng Haohui",
        "sex3": "男",
        "phone3": "15060125512",
        "p3Size": "XXXL"
    },
     {
        "tNumber": "52",
        "school": "中国地质大学（武汉）",
        "school2": "China University of Geosciences",
        "type": "会议费",
        "bank": "武汉市洪山区鲁磨路388号\n中国银行武汉地大支行",
        "taxNum": "420111441626770",
        "addr": "武汉市洪山区鲁磨路388号中国地质大学计算机学院张锋",
        "schoolContactName": "张锋",
        "schoolContactPhone": "18627010303",
        "coach": "张锋",
        "coach2": "Feng Zhang",
        "coachPhone": "18627010303",
        "coachEmail": "8125345@qq.com",
        "isCome": "是",
        "cSize": "L",
        "tName": "地大之光",
        "tNameE": "CUG Lightening",
        "tPerson1": "马超淳",
        "tPerson1E": "Chaochun Ma",
        "sex1": "男",
        "phone1": "13812351906",
        "p1Size": "XL",
        "tPerson2": " 冀全伟",
        "tPerson2E": "Quanwei Ji",
        "sex2": "男",
        "phone2": "15927514811",
        "p2Size": "XL",
        "tPerson3": "哈斯",
        "tPerson3E": "Si Ha",
        "sex3": "男",
        "phone3": "15927458169",
        "p3Size": "L"
    },
    {
        "tNumber": "53",
        "school": "南开大学",
        "school2": "Nankai University",
        "type": "会务费",
        "bank": "交通银行天津南开大学支行",
        "taxNum": "120104401359372",
        "addr": "天津市津南区海河教育园区同砚路38号南开大学津南校区理科组团计算机与控制工程学院",
        "schoolContactName": "王明鹏",
        "schoolContactPhone": "15822960346",
        "coach": "刘晓光",
        "coach2": "Xiaoguang Liu",
        "coachPhone": "18622291883",
        "coachEmail": "liuxg@ngjl.nankai.edu.cn",
        "isCome": "否",
        "cSize": 0,
        "tName": "冒号左圆括号右圆括号左花括号冒号或冒号与右花括号分号冒号(如果印不了这么多就印“印不开”)",
        "tNameE": ":(){ :|:& };:",
        "tPerson1": "王本亮",
        "tPerson1E": "Benlang Wang",
        "sex1": "男",
        "phone1": "13502060979",
        "p1Size": "XL",
        "tPerson2": "梁宸",
        "tPerson2E": "Chen Liang",
        "sex2": "男",
        "phone2": "13820227110",
        "p2Size": "XXXL",
        "tPerson3": "刘智博",
        "tPerson3E": "Zhibo Liu",
        "sex3": "男",
        "phone3": "15222291160",
        "p3Size": "XL"
    },
  {
        "tNumber": "54",
        "school": "江苏科技大学（张家港）",
        "school2": "Jiangsu university of science and technology ",
        "type": "竞赛费",
        "bank": "交通银行张家港分行",
        "taxNum": "52320000509200160J",
        "addr": "江苏省张家港市长兴中路8号江苏科技大学（张家港）",
        "schoolContactName": "李雪宝",
        "schoolContactPhone": "13405618011",
        "coach": "李雪宝",
        "coach2": "li xuebao",
        "coachPhone": "13405618011",
        "coachEmail": "305122880@qq.com",
        "isCome": "是",
        "cSize": "XL",
        "tName": "皮皮",
        "tNameE": "pipis",
        "tPerson1": "沈智勇",
        "tPerson1E": "zhiyong shen ",
        "sex1": "男",
        "phone1": "17768058801",
        "p1Size": "XL",
        "tPerson2": "章新越",
        "tPerson2E": "zhang xinyue ",
        "sex2": "男",
        "phone2": "17706248905",
        "p2Size": "XXL",
        "tPerson3": "周扬",
        "tPerson3E": "yang zhou",
        "sex3": "男",
        "phone3": "18361192808",
        "p3Size": "XL"
    },
     {
        "tNumber": "55",
        "school": "哈尔滨理工大学",
        "school2": "Harbin University Of Science And Technology",
        "type": "竞赛费",
        "bank": "中国工商银行哈尔滨市和兴支行 哈尔滨市南岗区和兴路108号",
        "taxNum": "122300004240104488",
        "addr": "黑龙江省哈尔滨市南岗区学府路52号哈尔滨理工大学（西区）104信箱",
        "schoolContactName": "金恩海",
        "schoolContactPhone": "13946059966",
        "coach": "于波",
        "coach2": "Yu Bo",
        "coachPhone": "13945142441",
        "coachEmail": "hrbust_yubo1981@163.com",
        "isCome": "是",
        "cSize": "XL",
        "tName": "队长跑路了，我们来旅游",
        "tNameE": "Captain ran away, we come to travel",
        "tPerson1": "宋增林",
        "tPerson1E": "Song Zenglin",
        "sex1": "男",
        "phone1": "18845046952",
        "p1Size": "XL",
        "tPerson2": "卢智达",
        "tPerson2E": "Lu Zhida",
        "sex2": "男",
        "phone2": "13009870920",
        "p2Size": "XL",
        "tPerson3": "甘炳钧",
        "tPerson3E": "Gan Bingjun",
        "sex3": "男",
        "phone3": "13019011922",
        "p3Size": "XL"
    },
     {
        "tNumber": "56",
        "school": "江南大学",
        "school2": "JiangNan University",
        "type": "会议费",
        "bank": "工商银行无锡江南大学支行",
        "taxNum": "1210000071780177X1",
        "addr": "江苏省无锡市滨湖区蠡湖大道1800号江南大学",
        "schoolContactName": "毛蕊",
        "schoolContactPhone": "18861813930",
        "coach": "蒋敏",
        "coach2": "Min Jiang",
        "coachPhone": "18861813930",
        "coachEmail": "1522310374@qq.com",
        "isCome": "是",
        "cSize": "L",
        "tName": "代码强迫症",
        "tNameE": "codeforces",
        "tPerson1": "毛蕊",
        "tPerson1E": "Rui Mao",
        "sex1": "女",
        "phone1": "18861813930",
        "p1Size": "M",
        "tPerson2": "邹智滔",
        "tPerson2E": "Zhitao Zou",
        "sex2": "男",
        "phone2": "18861815707",
        "p2Size": "L",
        "tPerson3": "赵祎",
        "tPerson3E": "Yi Zhao",
        "sex3": "男",
        "phone3": "13395110938",
        "p3Size": "L"
    },
   {
        "tNumber": "57",
        "school": "中国地质大学（北京）",
        "school2": "China University of Geosciences, Beijing",
        "type": "竞赛费",
        "bank": "中国农业银行股份有限公司北京地质大学分理处",
        "taxNum": "12100000400001221L",
        "addr": "北京市海淀区学院路29号",
        "schoolContactName": "邹卓君",
        "schoolContactPhone": "18810869630",
        "coach": "高翔",
        "coach2": "Xiang Gao",
        "coachPhone": "15011560580",
        "coachEmail": "gyshgx868@gmail.com",
        "isCome": "是",
        "cSize": "L",
        "tName": "哇！金色普通！",
        "tNameE": "WA！Golden Normal！",
        "tPerson1": "邹卓君",
        "tPerson1E": "Zhuojun Zou",
        "sex1": "女",
        "phone1": "18810869630",
        "p1Size": "L",
        "tPerson2": "李博",
        "tPerson2E": "Bo Li",
        "sex2": "男",
        "phone2": "18600354166",
        "p2Size": "XL",
        "tPerson3": "丁子富",
        "tPerson3E": "Zifu Ding",
        "sex3": "男",
        "phone3": "18811455059",
        "p3Size": "XL"
    },
    {
        "tNumber": "58",
        "school": "北京邮电大学",
        "school2": "Beijing University of Posts and Telecommunications",
        "type": "竞赛费",
        "bank": "北京市海淀区西土城路10号",
        "taxNum": "12100000400009952C",
        "addr": "北京市海淀区西土城路10号 北京邮电大学主楼912",
        "schoolContactName": "任琪宇",
        "schoolContactPhone": "15811468600",
        "coach": "孟祥武",
        "coach2": "MENG XIANGWU",
        "coachPhone": "13621036907",
        "coachEmail": "mengxw@bupt.edu.cn",
        "isCome": "是",
        "cSize": "XXL",
        "tName": "痛击我的队友",
        "tNameE": "protect my enemy",
        "tPerson1": "杨铁智",
        "tPerson1E": "Tiezhi Yang",
        "sex1": "男",
        "phone1": "13021205188",
        "p1Size": "M",
        "tPerson2": "李瀚铭",
        "tPerson2E": "LI HANMING",
        "sex2": "男",
        "phone2": "18810806158",
        "p2Size": "XXXL",
        "tPerson3": "程元",
        "tPerson3E": "DavidCheng",
        "sex3": "男",
        "phone3": "18810339563",
        "p3Size": "L"
    },
     {
        "tNumber": "59",
        "school": "杭州电子科技大学",
        "school2": "Hangzhou Dianzi University",
        "type": "参赛费",
        "bank": "工行杭州高新支行",
        "taxNum": "12330000470009026T",
        "addr": "杭州下沙高教园杭州电子科技大学计算机学院",
        "schoolContactName": "刘春英",
        "schoolContactPhone": "13486129712",
        "coach": "刘春英",
        "coach2": "LIU Chunying",
        "coachPhone": "13486129712",
        "coachEmail": "hduacm@qq.com",
        "isCome": "是",
        "cSize": "XXL",
        "tName": "杭电加特林",
        "tNameE": "HDU-Gatling",
        "tPerson1": "高翰林",
        "tPerson1E": "GAO Hanlin",
        "sex1": "男",
        "phone1": "18523232604",
        "p1Size": "L",
        "tPerson2": "朱家豪",
        "tPerson2E": "ZHU Jiahao",
        "sex2": "男",
        "phone2": "15968190866",
        "p2Size": "XL",
        "tPerson3": "江子特",
        "tPerson3E": "Jiang Zite",
        "sex3": "男",
        "phone3": "15968802230",
        "p3Size": "XXL"
    },
     {
        "tNumber": "60",
        "school": "集美大学",
        "school2": "JiMei University",
        "type": "竞赛费",
        "bank": " 福建省厦门市集美区集源路89号",
        "taxNum": "12350000426600329N",
        "addr": "厦门市集美区银江路185号",
        "schoolContactName": "林阳斌",
        "schoolContactPhone": "15060786995",
        "coach": "林阳斌",
        "coach2": "Yangbin Lin",
        "coachPhone": "15060786995",
        "coachEmail": "yblin@jmu.edu.cn",
        "isCome": "是",
        "cSize": "XL",
        "tName": "寄叶部队",
        "tNameE": "YoRHa",
        "tPerson1": "汤旭腾",
        "tPerson1E": "Xuteng Tang",
        "sex1": "男",
        "phone1": "13163996157",
        "p1Size": "XL",
        "tPerson2": "施亮伟",
        "tPerson2E": "Liangwei Shi",
        "sex2": "男",
        "phone2": "15080026100",
        "p2Size": "XL",
        "tPerson3": "蔡东强",
        "tPerson3E": "Dongqiang Cai",
        "sex3": "男",
        "phone3": "15659291947",
        "p3Size": "XXL"
    },
    {
        "tNumber": "61",
        "school": "山东科技大学",
        "school2": "Shandong University of Science and Technology",
        "type": "竞赛费",
        "bank": "农行青岛开发区支行",
        "taxNum": "37021149557059X",
        "addr": "青岛经济技术开发区前湾港路579号山海花园B1-201",
        "schoolContactName": "吴振寰",
        "schoolContactPhone": "13864221246",
        "coach": "吴振寰",
        "coach2": "Wu Zhenhuan ",
        "coachPhone": "13864221246",
        "coachEmail": "wu_zhenhuan@163.com",
        "isCome": "否",
        "cSize": 0,
        "tName": "圣剑号",
        "tNameE": "SKD26517 Excalibur",
        "tPerson1": "王硕",
        "tPerson1E": "Shuo Wang",
        "sex1": "男",
        "phone1": "15621048621",
        "p1Size": "XXXL",
        "tPerson2": "王荣勋",
        "tPerson2E": "Rongxun Wang",
        "sex2": "男",
        "phone2": "15562918519",
        "p2Size": "L",
        "tPerson3": "王文晖",
        "tPerson3E": "Wenhui Wang",
        "sex3": "男",
        "phone3": "17863959882",
        "p3Size": "L"
    },
     {
        "tNumber": "62",
        "school": "中山大学",
        "school2": "Sun Yat-sen University",
        "type": "会务费",
        "bank": "中国工商银行广州中山大学支行",
        "taxNum": "121000004558631445",
        "addr": "广州大学城中山大学东校园数据科学与计算机学院616E",
        "schoolContactName": "林瀚",
        "schoolContactPhone": "13711174851",
        "coach": "郭嵩山（奖状）/张子臻（带队）",
        "coach2": "Songshan Guo/Zizhen Zhang",
        "coachPhone": "13826411848",
        "coachEmail": "zhangzzh7@mail.sysu.edu.cn",
        "isCome": "否/是",
        "cSize": "XXL",
        "tName": "中山大学_死线之蓝",
        "tNameE": "SYSU_DeadBlue",
        "tPerson1": "吴统文",
        "tPerson1E": "tongwen wu",
        "sex1": "男",
        "phone1": "13719326757",
        "p1Size": "L",
        "tPerson2": "刘明航",
        "tPerson2E": "minghang liu",
        "sex2": "男",
        "phone2": "15880405959",
        "p2Size": "L",
        "tPerson3": "杨思翔",
        "tPerson3E": "sixiang yang",
        "sex3": "男",
        "phone3": "13719198199",
        "p3Size": "XL"
    },
     {
        "tNumber": "63",
        "school": "东北师范大学",
        "school2": "Northeast Normal University",
        "type": "参赛费",
        "bank": "中行长春自由大路支行",
        "taxNum": "220102423202747",
        "addr": "吉林省长春市净月大街2555号东北师范大学信息科学与技术学院",
        "schoolContactName": "周治国",
        "schoolContactPhone": "15943060634",
        "coach": "周治国",
        "coach2": "Zhiguo Zhou",
        "coachPhone": "15943060634",
        "coachEmail": "zhouzg281@nenu.edu.cn",
        "isCome": "是",
        "cSize": "L",
        "tName": "实力划水",
        "tNameE": "Power stroke",
        "tPerson1": "颜超一",
        "tPerson1E": "Chaoyi Yan",
        "sex1": "男",
        "phone1": "13287643886",
        "p1Size": "XL",
        "tPerson2": "王超",
        "tPerson2E": "Chao Wang",
        "sex2": "女",
        "phone2": "13756884727",
        "p2Size": "L",
        "tPerson3": "卫小琼",
        "tPerson3E": "Xiaoqiong Wei",
        "sex3": "女",
        "phone3": "13154312990",
        "p3Size": "L"
    },
     {
        "tNumber": "64",
        "school": "广州大学",
        "school2": "Guangzhou University",
        "type": "参赛费",
        "bank": "工行广州大学城中环支行",
        "taxNum": "‘124401007348911139",
        "addr": "广东省广州市广州大学城外环西路230号 广州大学 电子信息楼417室",
        "schoolContactName": "丘凯伦",
        "schoolContactPhone": "13392633771",
        "coach": "张为",
        "coach2": "Wei Zhang",
        "coachPhone": "18922168928",
        "coachEmail": "zwfyj@126.com",
        "isCome": "是",
        "cSize": "L",
        "tName": "记得买葡萄干",
        "tNameE": "PutaoGan!",
        "tPerson1": "廖崇灿",
        "tPerson1E": "Chongcan Liao",
        "sex1": "男",
        "phone1": "18825860513",
        "p1Size": "L",
        "tPerson2": "李立基",
        "tPerson2E": "Liji Li",
        "sex2": "男",
        "phone2": "17728151873",
        "p2Size": "L",
        "tPerson3": "温嘉宝",
        "tPerson3E": "Jiabao Wen",
        "sex3": "男",
        "phone3": "13247529454",
        "p3Size": "L"
    },
     {
        "tNumber": "65",
        "school": "南京晓庄学院",
        "school2": "Nanjing Xiaozhuang University",
        "type": "参赛费",
        "bank": "工行城东支行\n",
        "taxNum": "123201004258050154",
        "addr": "南京市江宁区弘景大道3601号",
        "schoolContactName": "周恺",
        "schoolContactPhone": "13655183024",
        "coach": "周恺",
        "coach2": "Kai Zhou",
        "coachPhone": "13655183024",
        "coachEmail": "kpskps@qq.com",
        "isCome": "是",
        "cSize": "XXXL",
        "tName": "香港记者",
        "tNameE": "HongKong reporter",
        "tPerson1": "马益帆",
        "tPerson1E": "Yifan Ma",
        "sex1": "男",
        "phone1": "18251815096",
        "p1Size": "xl",
        "tPerson2": "刘翔昊",
        "tPerson2E": "Xianghao Liu",
        "sex2": "男",
        "phone2": "13914567901",
        "p2Size": "xl",
        "tPerson3": "赵俊杰",
        "tPerson3E": "Junjie Zhao",
        "sex3": "男",
        "phone3": "17314985685",
        "p3Size": "l"
    },
   {
        "tNumber": "66",
        "school": "四川大学",
        "school2": "Sichuan University",
        "type": "竞赛费",
        "bank": "中国建设银行股份有限公司成都川大支行",
        "taxNum": "121000004000091949",
        "addr": "四川省成都市四川大学（江安）",
        "schoolContactName": "孙银凯",
        "schoolContactPhone": "18382020298",
        "coach": "左劼",
        "coach2": "Zuo Jie",
        "coachPhone": "13808098575",
        "coachEmail": "417220124@qq.com",
        "isCome": "是",
        "cSize": "M",
        "tName": "打完这场比赛就回老家结婚",
        "tNameE": "after this game,go back home to get maried",
        "tPerson1": "孙银凯",
        "tPerson1E": "Sun Yinkai",
        "sex1": "男",
        "phone1": "18382020298",
        "p1Size": "M",
        "tPerson2": "赖科行",
        "tPerson2E": "Lai Kehang",
        "sex2": "男",
        "phone2": "17796414510\n",
        "p2Size": "L",
        "tPerson3": "梁峰",
        "tPerson3E": "Liang Feng",
        "sex3": "男",
        "phone3": "18908016656",
        "p3Size": "M"
    },
     {
        "tNumber": "67",
        "school": "华东师范大学",
        "school2": "East China Normal University",
        "type": "参赛费",
        "bank": "工行上海市金沙江路支行",
        "taxNum": "12100000425006133D",
        "addr": "上海市普陀区中山北路3663号华东师范大学理科大楼B711",
        "schoolContactName": "肖春芸",
        "schoolContactPhone": "13816588138",
        "coach": "肖春芸/杜育根",
        "coach2": "Chunyun Xiao/Yugen Du",
        "coachPhone": "13816588138/13386039386",
        "coachEmail": "cyxiao@cs.ecnu.edu.cn/ygdu@sei.ecnu.edu.cn",
        "isCome": "是",
        "cSize": "L",
        "tName": "量子鸭嘴笔",
        "tNameE": "Quantum Engineering Drawing",
        "tPerson1": "金恺翔",
        "tPerson1E": "Kaixiang Jin",
        "sex1": "男",
        "phone1": "18916797212",
        "p1Size": "XL",
        "tPerson2": "林方欣",
        "tPerson2E": "Fangxin Lin",
        "sex2": "男",
        "phone2": "13008983853",
        "p2Size": "XL",
        "tPerson3": "胡星武",
        "tPerson3E": "Xingwu Hu",
        "sex3": "男",
        "phone3": "15618522341",
        "p3Size": "L"
    },
     {
        "tNumber": "68",
        "school": "香港科技大学",
        "school2": "Hong Kong University of Science and Technology",
        "type": "竞赛费",
        "bank": "空缺",
        "taxNum": "空缺",
        "addr": "香港清水湾香港科技大学A座408C室",
        "schoolContactName": "张浩千",
        "schoolContactPhone": "85290632087",
        "coach": "张浩千",
        "coach2": "Haoqian Zhang",
        "coachPhone": "85290632087",
        "coachEmail": "haoqian.zhang@connect.ust.hk",
        "isCome": "是",
        "cSize": "XXXL",
        "tName": "可愛的鹿鹿",
        "tNameE": "Lovely Luna",
        "tPerson1": "韩路新",
        "tPerson1E": "Luxin Han",
        "sex1": "男",
        "phone1": "17665390515",
        "p1Size": "XXL",
        "tPerson2": "薛博桓",
        "tPerson2E": "Bohuan Xue",
        "sex2": "男",
        "phone2": "13628338554",
        "p2Size": "M",
        "tPerson3": "林耿",
        "tPerson3E": "Geng Lin",
        "sex3": "男",
        "phone3": "15626008192",
        "p3Size": "XL"
    },
    {
        "tNumber": "69",
        "school": "西北大学",
        "school2": "Northwest University",
        "type": "竞赛费",
        "bank": "交通银行太白路支行",
        "taxNum": "610103435201274",
        "addr": "陕西省西安市西北大学长安校区",
        "schoolContactName": "冯筠",
        "schoolContactPhone": "13991159616",
        "coach": "冯筠",
        "coach2": "Feng Jun",
        "coachPhone": "13991159616",
        "coachEmail": "fengjun@nwu.edu.cn",
        "isCome": "否",
        "cSize": 0,
        "tName": "第一秒",
        "tNameE": "FristSecond",
        "tPerson1": "刘宇豪",
        "tPerson1E": "LIU Yuhao",
        "sex1": "男",
        "phone1": "13289202051",
        "p1Size": "L",
        "tPerson2": "黄庆东",
        "tPerson2E": "HUANG Qingdong",
        "sex2": "男",
        "phone2": "17602969458 ",
        "p2Size": "XL",
        "tPerson3": "张成",
        "tPerson3E": "Zhang Cheng",
        "sex3": "女",
        "phone3": "15249296708 ",
        "p3Size": "M"
    },
     {
        "tNumber": "70",
        "school": "东北大学",
        "school2": "Northeastern University",
        "type": "竞赛费",
        "bank": "建行沈阳东北大学支行",
        "taxNum": "1210000046300354XU",
        "addr": "东北大学浑南校区",
        "schoolContactName": "潘敏佳",
        "schoolContactPhone": "15804031792",
        "coach": "赵志滨",
        "coach2": "Zhibin Zhao",
        "coachPhone": "13709812813",
        "coachEmail": "centos@vip.qq.com",
        "isCome": "否",
        "cSize": 0,
        "tName": "Wings",
        "tNameE": "Wings",
        "tPerson1": "程国宇",
        "tPerson1E": "Guoyu Cheng",
        "sex1": "男",
        "phone1": "18240441060",
        "p1Size": "XXL",
        "tPerson2": "杨程皓",
        "tPerson2E": "Chenghao Yang",
        "sex2": "男",
        "phone2": "15566049100",
        "p2Size": "XL",
        "tPerson3": "李开均",
        "tPerson3E": "Kaijun Li",
        "sex3": "男",
        "phone3": "17624012306",
        "p3Size": "XL"
    },
     {
        "tNumber": "71",
        "school": "东北大学",
        "school2": "Northeastern University",
        "type": "竞赛费",
        "bank": "建行沈阳东北大学支行",
        "taxNum": "1210000046300354XU",
        "addr": "东北大学浑南校区",
        "schoolContactName": "潘敏佳",
        "schoolContactPhone": "15804031792",
        "coach": "李芳芳",
        "coach2": "Fangfang Li",
        "coachPhone": "13709812813",
        "coachEmail": "centos@vip.qq.com",
        "isCome": "否",
        "cSize": 0,
        "tName": "三只更咸的鱼",
        "tNameE": "Three saltier fish",
        "tPerson1": "余宝仑",
        "tPerson1E": "Baolun Yu",
        "sex1": "男",
        "phone1": "15940258437",
        "p1Size": "XXL",
        "tPerson2": "周子群",
        "tPerson2E": "Ziqun Zhou",
        "sex2": "男",
        "phone2": "13032468268",
        "p2Size": "XL",
        "tPerson3": "赵帅",
        "tPerson3E": "Shuai Zhao",
        "sex3": "男",
        "phone3": "13604003201",
        "p3Size": "XL"
    },
     {
        "tNumber": "72",
        "school": "南京航空航天大学",
        "school2": "\nNanjing University of Aeronautics and Astronautics",
        "type": "竞赛费",
        "bank": "交通银行南京御道街支行",
        "taxNum": "12100000466006826U",
        "addr": "江苏省南京市江宁区将军大道29号南航江宁校区",
        "schoolContactName": "邹春然",
        "schoolContactPhone": "13357730973",
        "coach": "邹春然",
        "coach2": "Zou Chunran",
        "coachPhone": "13357730973",
        "coachEmail": "zou.c@163.com",
        "isCome": "是",
        "cSize": "XXXL",
        "tName": "学习使我快乐",
        "tNameE": "Overwatch",
        "tPerson1": "黄振",
        "tPerson1E": "Huang Zhen",
        "sex1": "男",
        "phone1": "15950530516",
        "p1Size": "M",
        "tPerson2": "黄聿超",
        "tPerson2E": "Huang Yuchao",
        "sex2": "男",
        "phone2": "15651012239",
        "p2Size": "L",
        "tPerson3": "王天行",
        "tPerson3E": "Wang Tianxing",
        "sex3": "男",
        "phone3": "15950525815",
        "p3Size": "XXXL"
    },
     {
        "tNumber": "73",
        "school": "青岛大学",
        "school2": "Qingdao University",
        "type": "会议费",
        "bank": "青岛银行香港中路第二支行",
        "taxNum": "12370000495571728M",
        "addr": "山东省青岛市香港东路7号青岛大学数软学院",
        "schoolContactName": "张志梅",
        "schoolContactPhone": "13361296869",
        "coach": "张志梅",
        "coach2": "Zhang Zhimei",
        "coachPhone": "13361296869",
        "coachEmail": "zhangzm@qdu.edu.cn",
        "isCome": "否",
        "cSize": 0,
        "tName": "我们真的很不错",
        "tNameE": "We are really nice",
        "tPerson1": "林震",
        "tPerson1E": "Lucas",
        "sex1": "男",
        "phone1": "17866639398",
        "p1Size": "L",
        "tPerson2": "韩沁东",
        "tPerson2E": "ijrys ",
        "sex2": "男",
        "phone2": "17865429805",
        "p2Size": "XL",
        "tPerson3": "班寅虓",
        "tPerson3E": "Coly",
        "sex3": "男",
        "phone3": "18353116008",
        "p3Size": "XL"
    },
   {
        "tNumber": "74",
        "school": "天津大学",
        "school2": "Tianjin University",
        "type": "参赛费",
        "bank": " 天津银行兴科支行",
        "taxNum": "120104401359321",
        "addr": "天津市津南区雅观路135号天津大学北洋园校区47楼",
        "schoolContactName": "赵满坤",
        "schoolContactPhone": "13652185336",
        "coach": "于瑞国\n喻梅",
        "coach2": "Yu Ruiguo\nYu mei",
        "coachPhone": "13820383156\n15522308655",
        "coachEmail": "rgyu@tju.edu.cn\nyumei@tju.edu.cn",
        "isCome": "是\n是",
        "cSize": "XXXL\nL",
        "tName": "Tju_master_driver",
        "tNameE": "Tju_master_driver",
        "tPerson1": "贾天豪",
        "tPerson1E": "Tianhao Jia",
        "sex1": "男",
        "phone1": "13752209740",
        "p1Size": "L",
        "tPerson2": "田原",
        "tPerson2E": "Tian Yuan",
        "sex2": "男",
        "phone2": "18230226528",
        "p2Size": "XL",
        "tPerson3": "孙英洲",
        "tPerson3E": "Sun Yingzhou",
        "sex3": "男",
        "phone3": "13207527113",
        "p3Size": "XL"
    },
     {
        "tNumber": "75",
        "school": "南昌理工学院",
        "school2": "Nanchang Institute of Technology",
        "type": "竞赛费",
        "bank": " 建行南昌市洪城大市场支行",
        "taxNum": "52360000727756749C",
        "addr": "江西省南昌市迎宾大道1155号康城64栋",
        "schoolContactName": "赵欢",
        "schoolContactPhone": "13870067109",
        "coach": "赵欢",
        "coach2": "Huan Zhao",
        "coachPhone": "13870067109",
        "coachEmail": "30476597@qq.com",
        "isCome": "是",
        "cSize": "M",
        "tName": "先锋",
        "tNameE": "pioneer",
        "tPerson1": "邹洋洋",
        "tPerson1E": "Yangyang Zou",
        "sex1": "男",
        "phone1": "15797878058",
        "p1Size": "M",
        "tPerson2": "王程远",
        "tPerson2E": "Chengyuan Wang",
        "sex2": "男",
        "phone2": "17770809742",
        "p2Size": "XL",
        "tPerson3": "衷鑫",
        "tPerson3E": "XinZhong",
        "sex3": "男",
        "phone3": "18179175539",
        "p3Size": "M"
    },
    {
        "tNumber": "76",
        "school": "石河子大学",
        "school2": "Shihezi University",
        "type": "竞赛费",
        "bank": "中国银行石河子市分行石河子大学支行",
        "taxNum": "12990000458493855B",
        "addr": "新疆石河子市石河子大学信息科学与技术学院",
        "schoolContactName": "高攀",
        "schoolContactPhone": "13179930011",
        "coach": "高攀",
        "coach2": "Gao Pan",
        "coachPhone": "13179930011",
        "coachEmail": "15207175@qq.com",
        "isCome": "是",
        "cSize": "XXL",
        "tName": "附属幼儿园",
        "tNameE": "cute kindergarten",
        "tPerson1": "任媛媛",
        "tPerson1E": "Yuanyuan Ren",
        "sex1": "女",
        "phone1": "18999802855",
        "p1Size": "M",
        "tPerson2": "姚亚军",
        "tPerson2E": "Yajun Yao",
        "sex2": "男",
        "phone2": "15699333882",
        "p2Size": "XL",
        "tPerson3": "杨锐",
        "tPerson3E": "Rui Yang",
        "sex3": "男",
        "phone3": "18671746427",
        "p3Size": "XL"
    },
    {
        "tNumber": "77",
        "school": "石河子大学",
        "school2": "Shihezi University",
        "type": "竞赛费",
        "bank": "中国银行石河子市分行石河子大学支行",
        "taxNum": "12990000458493855B",
        "addr": "新疆石河子市石河子大学信息科学与技术学院",
        "schoolContactName": "高攀",
        "schoolContactPhone": "13179930011",
        "coach": "汪传建",
        "coach2": "Wang Chuanjian",
        "coachPhone": "13179930011",
        "coachEmail": "15207175@qq.com",
        "isCome": "是",
        "cSize": "XL",
        "tName": "吃鸡队",
        "tNameE": "ohayo team",
        "tPerson1": "袁文杰",
        "tPerson1E": "Wenjie Yuan",
        "sex1": "男",
        "phone1": "13150406721",
        "p1Size": "L",
        "tPerson2": "韦文强",
        "tPerson2E": "Wenqiang Wei",
        "sex2": "男",
        "phone2": "15352604907",
        "p2Size": "XXL",
        "tPerson3": "赵星标",
        "tPerson3E": "Xingbiao Zhao",
        "sex3": "男",
        "phone3": "18899537880",
        "p3Size": "XL"
    },
     {
        "tNumber": "78",
        "school": "同济大学",
        "school2": "Tongji University",
        "type": "竞赛费",
        "bank": "中国农业银行股份有限公司上海翔殷支行（五角场支行营业部）",
        "taxNum": "12100000425006125J",
        "addr": "上海市嘉定区曹安公路4800号同济大学",
        "schoolContactName": "张恩伟",
        "schoolContactPhone": "18817870839",
        "coach": "叶晨",
        "coach2": "Chen Ye",
        "coachPhone": "13301616882",
        "coachEmail": "yechen@tongji.edu.cn",
        "isCome": "是否参加现场赛",
        "cSize": "xxxL",
        "tName": "捷尔任斯基观摩团",
        "tNameE": "dzerzhinski observation group",
        "tPerson1": "莫毅舟",
        "tPerson1E": "Yizhou Mo",
        "sex1": "男",
        "phone1": "18818213696",
        "p1Size": "M",
        "tPerson2": "欧阳小伟",
        "tPerson2E": "Xiaowei Ouyang",
        "sex2": "男",
        "phone2": "18916215535",
        "p2Size": "L",
        "tPerson3": "任秋宇",
        "tPerson3E": "Qiuyu Ren",
        "sex3": "男",
        "phone3": "13920666292",
        "p3Size": "L"
    },
     {
        "tNumber": "79",
        "school": "电子科技大学",
        "school2": "University of Electronic Science and Technology of China",
        "type": "会务费",
        "bank": "建行成都新鸿支行",
        "taxNum": "121000004507193117",
        "addr": "四川省成都市高新西区西源大道2006号电子科技大学清水河校区",
        "schoolContactName": "秦义茼",
        "schoolContactPhone": "18103138494",
        "coach": "吴磊",
        "coach2": "Lei Wu",
        "coachPhone": "13084443881",
        "coachEmail": "acm@uestc.edu.cn",
        "isCome": "是",
        "cSize": "XL",
        "tName": "UESTC_不如去上海坐磁悬浮吧",
        "tNameE": "UESTC_Maglev",
        "tPerson1": "杨宇同",
        "tPerson1E": "Yutong Yang",
        "sex1": "男",
        "phone1": "13402846105",
        "p1Size": "L",
        "tPerson2": "沈柯",
        "tPerson2E": "Ke Shen",
        "sex2": "男",
        "phone2": "13408031803",
        "p2Size": "XL",
        "tPerson3": "徐浩",
        "tPerson3E": "Hao Xu",
        "sex3": "男",
        "phone3": "18328564944",
        "p3Size": "XL"
    },
     {
        "tNumber": "80",
        "school": "电子科技大学",
        "school2": "University of Electronic Science and Technology of China",
        "type": "会务费",
        "bank": "建行成都新鸿支行",
        "taxNum": "121000004507193117",
        "addr": "四川省成都市高新西区西源大道2006号电子科技大学清水河校区",
        "schoolContactName": "秦义茼",
        "schoolContactPhone": "18103138494",
        "coach": "汪小平",
        "coach2": "Xiaoping Wang",
        "coachPhone": "18140169101",
        "coachEmail": "acm@uestc.edu.cn",
        "isCome": "是",
        "cSize": "XL",
        "tName": "UESTC_你的头发还好吗",
        "tNameE": "UESTC_p90RushB",
        "tPerson1": "谭胜松",
        "tPerson1E": "Shengsong Tan",
        "sex1": "男",
        "phone1": "15528369736",
        "p1Size": "L",
        "tPerson2": "周昊",
        "tPerson2E": "Hao Zhou",
        "sex2": "男",
        "phone2": "18482263687",
        "p2Size": "XL",
        "tPerson3": "钟望",
        "tPerson3E": "Wang Zhong",
        "sex3": "男",
        "phone3": "15279922160",
        "p3Size": "L"
    },
   {
        "tNumber": "81",
        "school": "电子科技大学",
        "school2": "University of Electronic Science and Technology of China",
        "type": "会务费",
        "bank": "建行成都新鸿支行",
        "taxNum": "121000004507193117",
        "addr": "四川省成都市高新西区西源大道2006号电子科技大学清水河校区",
        "schoolContactName": "秦义茼",
        "schoolContactPhone": "18103138494",
        "coach": 0,
        "coach2": 0,
        "coachPhone": 0,
        "coachEmail": 0,
        "isCome": 0,
        "cSize": 0,
        "tName": "UESTC_续",
        "tNameE": "UESTC_Continue",
        "tPerson1": "罗综颖",
        "tPerson1E": "Zongying Luo",
        "sex1": "男",
        "phone1": "15928908074",
        "p1Size": "L",
        "tPerson2": "张志斌",
        "tPerson2E": "Zhibing Zhang",
        "sex2": "男",
        "phone2": "13568976804",
        "p2Size": "L",
        "tPerson3": "叶鉴赏",
        "tPerson3E": "Jianshang Ye",
        "sex3": "男",
        "phone3": "15520767191",
        "p3Size": "L"
    },
     {
        "tNumber": "82",
        "school": "N/A",
        "school2": "N/A",
        "type": "个人参赛无需发票",
        "bank": "N/A",
        "taxNum": "N/A",
        "addr": "北京市北辰西路8号院北辰世纪中心A座",
        "schoolContactName": "陈伟颖",
        "schoolContactPhone": "15601121133",
        "coach": "张晴川",
        "coach2": "Qingchuan Zhang",
        "coachPhone": "19021171929",
        "coachEmail": "fsszns@163.com",
        "isCome": "是",
        "cSize": "L",
        "tName": "幻觉",
        "tNameE": "illusion",
        "tPerson1": "施韩原",
        "tPerson1E": "Hanyuan Shi",
        "sex1": "男",
        "phone1": "15216677522",
        "p1Size": "XL",
        "tPerson2": "李文昊",
        "tPerson2E": "Wenhao Li",
        "sex2": "男",
        "phone2": "18818270285",
        "p2Size": "L",
        "tPerson3": "陈伟颖",
        "tPerson3E": "Weiying Chen",
        "sex3": "女",
        "phone3": "15601121133",
        "p3Size": "L"
    },
    {
        "tNumber": "83",
        "school": "西北工业大学",
        "school2": "Northwestern Polytechnical University",
        "type": "参赛费",
        "bank": "工行西安西工大支行",
        "taxNum": "610103435231705",
        "addr": "陕西省西安市友谊西路127号",
        "schoolContactName": "刘君瑞",
        "schoolContactPhone": "13991350873",
        "coach": "姜学锋",
        "coach2": "Xuefeng Jiang",
        "coachPhone": "18991215916",
        "coachEmail": "jxf@nwpu.edu.cn",
        "isCome": "否",
        "cSize": 0,
        "tName": "东云研究所",
        "tNameE": "NPU_Shinonome Lab",
        "tPerson1": "蔡欣强",
        "tPerson1E": "Xinqiang Cai",
        "sex1": "男",
        "phone1": "15991454891",
        "p1Size": "XL",
        "tPerson2": "张伟佳",
        "tPerson2E": "Weijia Zhang",
        "sex2": "男",
        "phone2": "18626461360",
        "p2Size": "XL",
        "tPerson3": "陆苏",
        "tPerson3E": "Su Lu",
        "sex3": "男",
        "phone3": "15991794377",
        "p3Size": "L"
    },
    {
        "tNumber": "84",
        "school": "西北工业大学",
        "school2": "Northwestern Polytechnical University",
        "type": "参赛费",
        "bank": "工行西安西工大支行",
        "taxNum": "610103435231705",
        "addr": "陕西省西安市友谊西路127号",
        "schoolContactName": "刘君瑞",
        "schoolContactPhone": "13991350873",
        "coach": "姜学锋",
        "coach2": "Xuefeng Jiang",
        "coachPhone": "18991215916",
        "coachEmail": "jxf@nwpu.edu.cn",
        "isCome": "否",
        "cSize": 0,
        "tName": "题难还是人简单",
        "tNameE": "NPU_Hard Problems or Naive Persons",
        "tPerson1": "苏斌",
        "tPerson1E": "Bin Su",
        "sex1": "男",
        "phone1": "18629651530",
        "p1Size": "XL",
        "tPerson2": "高晨雨",
        "tPerson2E": "Chenyu Gao",
        "sex2": "女",
        "phone2": "13579867928",
        "p2Size": "M",
        "tPerson3": "赵志强",
        "tPerson3E": "Zhiqiang Zhao",
        "sex3": "男",
        "phone3": "17782584211",
        "p3Size": "L"
    },
    {
        "tNumber": "85",
        "school": "北京信息科技大学",
        "school2": "Beijing Information Science & Technology University",
        "type": "竞赛费",
        "bank": "北京银行学知支行 \n",
        "taxNum": "110108690805171 ",
        "addr": "北京朝阳区北四环中路35号北京信息大学健翔桥校区 ",
        "schoolContactName": "朱宇婷",
        "schoolContactPhone": "15600992107",
        "coach": "牟永敏",
        "coach2": "Yongmin Mu",
        "coachPhone": "15600992107",
        "coachEmail": "zyt_bob@163.com",
        "isCome": "是",
        "cSize": "XXXL",
        "tName": "百战炼磨",
        "tNameE": "Be a veteran in battle",
        "tPerson1": "周建亭",
        "tPerson1E": "Jianting Zhou",
        "sex1": "男",
        "phone1": "13856434195",
        "p1Size": "XL",
        "tPerson2": "徐文栋",
        "tPerson2E": "Wendong Xu",
        "sex2": "男",
        "phone2": "13856434195",
        "p2Size": "L",
        "tPerson3": "王朗",
        "tPerson3E": "Lang Wang",
        "sex3": "男",
        "phone3": "13856434195",
        "p3Size": "XL"
    },
     {
        "tNumber": "86",
        "school": "郑州轻工业学院",
        "school2": "Zhengzhou University of Light Industry",
        "type": "竞赛费",
        "bank": "工行郑州东风路支行",
        "taxNum": "410105415804596",
        "addr": "郑州市高新区科学大道136号郑州轻工业学院",
        "schoolContactName": "李晔",
        "schoolContactPhone": "13838152396",
        "coach": "李晔",
        "coach2": "Ye Li",
        "coachPhone": "13838152396",
        "coachEmail": "liye_ie@126.com",
        "isCome": "是",
        "cSize": "M",
        "tName": "踏雪无痕",
        "tNameE": "Pass without Trace",
        "tPerson1": "王家豪",
        "tPerson1E": "Jiahao Wang",
        "sex1": "男",
        "phone1": "18539112031",
        "p1Size": "L",
        "tPerson2": "殷杰飞",
        "tPerson2E": "Jiefei Yin",
        "sex2": "男",
        "phone2": "13283827641",
        "p2Size": "XXL",
        "tPerson3": "葛聪圣",
        "tPerson3E": "Congsheng Ge",
        "sex3": "男",
        "phone3": "15638518827",
        "p3Size": "XL"
    },
     {
        "tNumber": "87",
        "school": "江西财经大学",
        "school2": "JIANGXI UNIVERSITY OF FINANCE AND ECONOMICS ",
        "type": "竞赛费",
        "bank": "工行财大支行",
        "taxNum": "360107491018247",
        "addr": "江西省南昌市昌北经济开发区江西财经大学麦庐园校区",
        "schoolContactName": "赖长权",
        "schoolContactPhone": "15797706754",
        "coach": "魏丽军",
        "coach2": "Lijun Wei ",
        "coachPhone": "13879148424",
        "coachEmail": "villagerwei@gmail.com",
        "isCome": "是",
        "cSize": "XL",
        "tName": "JXUFE_求你马老公抱",
        "tNameE": "QiuNiMaLaoGongBao",
        "tPerson1": "赖长权",
        "tPerson1E": "Changquan Lai",
        "sex1": "男",
        "phone1": "15797706754",
        "p1Size": "S",
        "tPerson2": "钟裕",
        "tPerson2E": "Yu Zhong",
        "sex2": "男",
        "phone2": "18879963273",
        "p2Size": "L",
        "tPerson3": "邹卫东",
        "tPerson3E": "Weidong Zou",
        "sex3": "男",
        "phone3": "13870897454",
        "p3Size": "M"
    },
     {
        "tNumber": "88",
        "school": "江西财经大学",
        "school2": "JIANGXI UNIVERSITY OF FINANCE AND ECONOMICS ",
        "type": "竞赛费",
        "bank": "工行财大支行",
        "taxNum": "360107491018247",
        "addr": "江西省南昌市昌北经济开发区江西财经大学麦庐园校区",
        "schoolContactName": "尹爱华",
        "schoolContactPhone": "13979192393",
        "coach": "尹爱华",
        "coach2": "aihua yin",
        "coachPhone": "13979192393",
        "coachEmail": "826555671@qq.com",
        "isCome": "是",
        "cSize": "L",
        "tName": "ACM 再爱我一次",
        "tNameE": "ACM love me once more",
        "tPerson1": "黄江海",
        "tPerson1E": "Jianghai Huang",
        "sex1": "男",
        "phone1": "13027230680",
        "p1Size": "M",
        "tPerson2": "白禹",
        "tPerson2E": "yubai ",
        "sex2": "男  ",
        "phone2": "17612776768 ",
        "p2Size": "L ",
        "tPerson3": "吴臻",
        "tPerson3E": "zhen wu",
        "sex3": "男",
        "phone3": "18179249039",
        "p3Size": "L"
    },
    {
        "tNumber": "89",
        "school": "浙江工业大学",
        "school2": "Zhejiang University of Technology",
        "type": "参赛费",
        "bank": "中国农业银行杭州朝晖支行",
        "taxNum": "33010347000441X",
        "addr": "浙江省杭州市西湖区留和路288号浙江工业大学",
        "schoolContactName": "韩姗姗",
        "schoolContactPhone": "13757146533",
        "coach": "侯向辉",
        "coach2": "Hou Xianghui",
        "coachPhone": "13588746900",
        "coachEmail": "20640021@qq.com",
        "isCome": "是",
        "cSize": "XXL",
        "tName": "ZJUT1",
        "tNameE": "ZJUT1",
        "tPerson1": "黄坤",
        "tPerson1E": "Huang Kun",
        "sex1": "男",
        "phone1": "15957145961",
        "p1Size": "XXXL",
        "tPerson2": "陶宇星",
        "tPerson2E": "Tao Yuxing",
        "sex2": "男",
        "phone2": "15869189617",
        "p2Size": "XL",
        "tPerson3": "张水强",
        "tPerson3E": "Zhang Shuiqiang",
        "sex3": "男",
        "phone3": "15868801714",
        "p3Size": "XL"
    },
     {
        "tNumber": "90",
        "school": "华南理工大学",
        "school2": "South China University of Technology",
        "type": "竞赛费",
        "bank": "工行广州五山支行",
        "taxNum": "12100000455414429R",
        "addr": "广东省广州市番禺区小谷围街道星汇文华一期",
        "schoolContactName": "刘捷",
        "schoolContactPhone": "13760786615",
        "coach": "冼楚华",
        "coach2": "Xian Chuhua",
        "coachPhone": "13265179183",
        "coachEmail": "chhxian@scut.edu.cn",
        "isCome": "是",
        "cSize": "M",
        "tName": "红队列",
        "tNameE": "RedQueue",
        "tPerson1": "邵逸臻",
        "tPerson1E": "Shao Yizhen",
        "sex1": "男",
        "phone1": "13422383398",
        "p1Size": "XL",
        "tPerson2": "祝叶",
        "tPerson2E": "Zhu Ye",
        "sex2": "男",
        "phone2": "18813298254",
        "p2Size": "M",
        "tPerson3": "郭宇",
        "tPerson3E": "Guo Yu",
        "sex3": "男",
        "phone3": "18826076681",
        "p3Size": "XL"
    },
     {
        "tNumber": "91",
        "school": "华南理工大学",
        "school2": "South China University of Technology",
        "type": "竞赛费",
        "bank": "工行广州五山支行",
        "taxNum": "12100000455414429R",
        "addr": "广东省广州市番禺区小谷围街道星汇文华一期",
        "schoolContactName": "刘捷",
        "schoolContactPhone": "13760786615",
        "coach": "刘捷",
        "coach2": "Liu Jie",
        "coachPhone": "13760786615",
        "coachEmail": "seliujie@scut.edu.cn",
        "isCome": "是",
        "cSize": "XL",
        "tName": "喷火龙",
        "tNameE": "Charizard",
        "tPerson1": "林洋洲",
        "tPerson1E": "Lin Yangzhou",
        "sex1": "男",
        "phone1": "18923391689",
        "p1Size": "XXL",
        "tPerson2": "司马驰骏",
        "tPerson2E": "Sima Chijun",
        "sex2": "男",
        "phone2": "13825220538",
        "p2Size": "XL",
        "tPerson3": "杨凌云",
        "tPerson3E": "Yang Lingyun",
        "sex3": "男",
        "phone3": "13502846103",
        "p3Size": "M"
    },
    {
        "tNumber": "92",
        "school": "东华大学",
        "school2": "Donghua university",
        "type": "竞赛费",
        "bank": "工行上海市松江支行",
        "taxNum": "310105425006176",
        "addr": "上海市松江区文汇路300弄二期学生公寓24号楼4012室",
        "schoolContactName": "汪聪",
        "schoolContactPhone": "18321256109",
        "coach": "朱国进",
        "coach2": "Guojin Zhu",
        "coachPhone": "13564527721",
        "coachEmail": "gjzhu.dhu@163.com",
        "isCome": "是",
        "cSize": "M",
        "tName": "东华大学",
        "tNameE": "DHU",
        "tPerson1": "赵婉婷",
        "tPerson1E": "Wanting Zhao",
        "sex1": "女",
        "phone1": "18317095573",
        "p1Size": "M",
        "tPerson2": "汪聪",
        "tPerson2E": "Cong Wang",
        "sex2": "男",
        "phone2": "18321256109",
        "p2Size": "XL",
        "tPerson3": "施文俊",
        "tPerson3E": "Wenjun Shi",
        "sex3": "男",
        "phone3": "13661775002",
        "p3Size": "L"
    },
     {
        "tNumber": "93",
        "school": "西南科技大学",
        "school2": "Southwest University of Science and Technology",
        "type": "竞赛费",
        "bank": "绵阳市农行西南科技大学支行",
        "taxNum": "125100007175954436",
        "addr": "四川省绵阳市涪城区青义镇西南科技大学东6B507",
        "schoolContactName": "李洋阳",
        "schoolContactPhone": "15681931737",
        "coach": "谭顺华",
        "coach2": "Shunhua Tan",
        "coachPhone": "13881194123",
        "coachEmail": "w703710691d@163.com",
        "isCome": "是",
        "cSize": "XXL",
        "tName": "新年快乐",
        "tNameE": "Happy New Year",
        "tPerson1": "龙家琳",
        "tPerson1E": "Jialin Long",
        "sex1": "男",
        "phone1": "18681607205",
        "p1Size": "L",
        "tPerson2": "梁晨",
        "tPerson2E": "Chen Liang",
        "sex2": "男",
        "phone2": "13541992286",
        "p2Size": "L",
        "tPerson3": "黄思寒",
        "tPerson3E": "Sihan Huang",
        "sex3": "女",
        "phone3": "15882417385",
        "p3Size": "XL"
    },
     {
        "tNumber": "94",
        "school": "重庆邮电大学",
        "school2": "Chongqing University of Posts and Telecommunications",
        "type": "竞赛费",
        "bank": "工行重庆南山支行",
        "taxNum": "125000004504018996",
        "addr": "重庆市南岸区崇文路2号",
        "schoolContactName": "甘玲",
        "schoolContactPhone": "023-62461257",
        "coach": "甘玲",
        "coach2": "Ling Gan",
        "coachPhone": "15923263152",
        "coachEmail": "16475383@qq.com",
        "isCome": "是",
        "cSize": "L",
        "tName": "春风十里不如你",
        "tNameE": "unity",
        "tPerson1": "秦锐锋",
        "tPerson1E": "Ruifeng Qin",
        "sex1": "男",
        "phone1": "17784458863\n",
        "p1Size": "L",
        "tPerson2": "梁炬鸿",
        "tPerson2E": "Juhong Liang",
        "sex2": "男",
        "phone2": "18375975436",
        "p2Size": "L",
        "tPerson3": "牟星任",
        "tPerson3E": "Xingren Mou",
        "sex3": "男",
        "phone3": "18883142678",
        "p3Size": "L"
    },
     {
        "tNumber": "95",
        "school": "上海交通大学",
        "school2": "Shanghai Jiao Tong University",
        "type": "会务费",
        "bank": "中国银行上海市交通大学分行上海市东川路800号",
        "taxNum": "1210000042500615X0",
        "addr": "上海市闵行区东川路800号上海交通大学逸夫楼308房间",
        "schoolContactName": "方博慧",
        "schoolContactPhone": "18221829714",
        "coach": "俞勇",
        "coach2": "Yong Yu",
        "coachPhone": "13501778884",
        "coachEmail": "yyu@apex.sjtu.edu.cn",
        "isCome": "否",
        "cSize": 0,
        "tName": "夜幕",
        "tNameE": "Nightfall",
        "tPerson1": "秋闻达",
        "tPerson1E": "Wenda Qiu",
        "sex1": "男",
        "phone1": "13764295180",
        "p1Size": "M",
        "tPerson2": "罗中瑭",
        "tPerson2E": "Zhongtang Luo",
        "sex2": "男",
        "phone2": "13918980608",
        "p2Size": "XL",
        "tPerson3": "李泊宁",
        "tPerson3E": "Boning Li",
        "sex3": "男",
        "phone3": "15821931293",
        "p3Size": "XL"
    },
    {
        "tNumber": "96",
        "school": "清华大学",
        "school2": "Tsinghua University",
        "type": "竞赛费",
        "bank": "工行海淀西区支行",
        "taxNum": "12100000400000624D",
        "addr": "北京市海淀区清华大学东主楼8区500",
        "schoolContactName": "邬晓钧",
        "schoolContactPhone": "13810631521",
        "coach": "邬晓钧",
        "coach2": "WU, Xiaojun",
        "coachPhone": "13810631521",
        "coachEmail": "xjwu@tsinghua.edu.cn",
        "isCome": "是",
        "cSize": "XL",
        "tName": "马上就要被楼下超过了",
        "tNameE": "Overtaken by Downstairs Soon",
        "tPerson1": "张瑞喆",
        "tPerson1E": "ZHANG, Ruizhe",
        "sex1": "男",
        "phone1": "13717779751",
        "p1Size": "XL",
        "tPerson2": "于纪平",
        "tPerson2E": "YU, Jiping",
        "sex2": "男",
        "phone2": "13041160060",
        "p2Size": "L",
        "tPerson3": "汪乐平",
        "tPerson3E": "WANG, Leping",
        "sex3": "男",
        "phone3": "18810930208",
        "p3Size": "XL"
    },
     {
        "tNumber": "97",
        "school": "福建师范大学",
        "school2": "Fujian Normal University",
        "type": "竞赛费",
        "bank": 0,
        "taxNum": "12350000488001209F",
        "addr": "福建省福州市闽侯县科技路1号福建师范大学",
        "schoolContactName": "林辰寅",
        "schoolContactPhone": "18965568268",
        "coach": "吴闻",
        "coach2": "Wen Wu",
        "coachPhone": "13850138018",
        "coachEmail": "owen@fjnu.edu.cn",
        "isCome": "是",
        "cSize": "L",
        "tName": "无可奉告",
        "tNameE": "Clearlove Plus",
        "tPerson1": "林辰寅",
        "tPerson1E": "Chenyin Lin",
        "sex1": "男",
        "phone1": "18965568268",
        "p1Size": "L码",
        "tPerson2": "余伟强",
        "tPerson2E": "Weiqiang Yu",
        "sex2": "男",
        "phone2": "15705934041",
        "p2Size": "L码",
        "tPerson3": "赵嘉诚",
        "tPerson3E": "Jiacheng Zhao",
        "sex3": "男",
        "phone3": "13055794300",
        "p3Size": "L码"
    }
]

// for(var i = 0; i < 96; i++){
//     json[i].password1 = json[i].phone1;
//     json[i].password2 = json[i].phone2;
//     json[i].password3 = json[i].phone3;
//     json[i].uPhotoPath1 = null;
//     json[i].uPhotoPath2 = null;
//     json[i].uPhotoPath3 = null;
//     db.insertOne("teamAll",json[i],function (err, result) {
//         ;
//     });
// }
console.log(json[1]);

// db.insertOne("users",{"uId":1,
//     "uTeam":"defaultTeam",
//     "username":"admin@admin.admin",
//     "uName":"陈彬杰",
//     "uPhone":"15199170230",
//     "passaword":"15199170230",
//     "uPhotoPath":"/upload/新疆大学_defaultTeam_admin_陈彬杰",
//     "uSchool":"新疆大学"});
